### ISSUE TITLE
Wiki - broken link 

### ISSUE THREAD

**Issue by typxxi** [helgeerbe/OpenDTU-OnBattery#1013]
### What happened?

error 404 on the first / main wiki page in this first chapter "dynamic power limiter"

What is OpenDTU-OnBattery
OpenDTU-OnBattery is an extension of the original OpenDTU to support battery chargers, battery management systems (BMS) and power meters on a single ESP32. With the help of a [dynamic power limiter](https://github.com/helgeerbe/OpenDTU-OnBattery/Dynamic-Power-Limiter), the power production can be adjusted to the actual consumption. In this way, it is possible to come as close as possible to the goal of zero feed-in 

### To Reproduce Bug

Open the wiki page and click on the "dynamic power limiter" in the first paragraph

### Expected Behavior

it should open the existing page for "dynamic power limiter" 
I guess the one on the right navigation pane is meant. 

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

none - just Wiki 

### Anything else?

great work and documentation which is really full of details and knowledge over a really broad setup or use cases !

Thanks

**Comment by Manos1966** [comment]
Good catch 👍 

Fixed!
