### ISSUE TITLE
Stromzähler Einstellungen Problem 

### ISSUE THREAD

**Issue by Omermann** [helgeerbe/OpenDTU-OnBattery#1016]
### What happened?

Ich habe gestern die neue Version heruntergeladen

### To Reproduce Bug

Die Messung ergibt immer das Gleiche

### Expected Behavior

![IMG_6866](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/b2eecff0-2ac0-4ac5-85e9-e8857a7d9b90)
![IMG_6865](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/3ebef46a-f42e-43ec-942e-7096c68bb10d)
![IMG_6864](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/295b0983-a265-44bd-8307-d88eff8b3682)
![IMG_6863](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/7a1d727a-9b8e-4181-b25e-443433ea4fd1)
![IMG_6862](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/126a05dc-58b0-4408-b552-8216781b8974)
![IMG_6861](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/e17362f4-6822-4e72-bffc-85455b794a35)
![IMG_6860](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/73817c90-2e79-4325-b965-561bd7acdf72)
![IMG_6859](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/4cd9c229-a46b-473f-bc0d-db6ddc850576)
![IMG_6858](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/7c2651a0-bab9-4274-903f-ef40c9e42c67)

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

2024.05.07

**Comment by Omermann** [comment]
HM1500
shelly3em (nicht Pro Version)

**Comment by spcqike** [comment]
Die Einheit im Stromzähler ist wahrscheinlich falsch.

**Comment by Omermann** [comment]
Es funktionierte einwandfrei, bis ich die neue Version installierte. Nach der Installation passierte dies.

**Comment by spcqike** [comment]
Kann sein. 

Je nachdem, welche Version du hattest, gab es die Einstellung der Einheit bereits oder auch nicht 

aktuell steht halt „mW“ drin auf dem Bild. Damit werden die Leistungen eben als solche interpretiert. 333mW wären dann eben nur 0.33W, gerundet wahrscheinlich 0. 


bzw. was genau meinst du eigentlich mit deinem Problem? „Die Messung ergibt immer das gleiche“? 

OpenDTU misst die Leistung nicht. Sie wird von Shelly abgerufen. 

Was sagt der Shelly denn, wenn du die URL  im Browser aufrufst?

**Comment by Omermann** [comment]
„Die Messung ergibt immer das gleiche“?
Success! Power: 333946.81W. Immer gleich kw mW oder Watt.
Shelly es funktioniert ohne Problem.
Nach dem Update gestern hat es nicht funktioniert
![IMG_6867](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/4c95f7b7-4873-43aa-ac98-4e821c43bd34)

**Comment by schlimmchen** [comment]
Aus deinen Screenshots:
![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3578416/698e209a-c622-40ee-9df9-852a943b7d8e)

> Success! Power: 333946.81W. Immer gleich kw mW oder Watt.

Bei dieser Ausgabe hattest du wohl kW eingestelt?

Also ich hab auch noch nicht begriffen, was hier das Problem ist...

Bitte kopiere die im PowerMeter eingestellt URL in deinen Browser und zeig uns, was dann zurückkommt.

**Comment by Omermann** [comment]
> Aus deinen Screenshots: ![image](https://private-user-images.githubusercontent.com/3578416/335813628-698e209a-c622-40ee-9df9-852a943b7d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjI4MTMsIm5iZiI6MTcxNzI2MjUxMywicGF0aCI6Ii8zNTc4NDE2LzMzNTgxMzYyOC02OThlMjA5YS1jNjIyLTQwZWUtOWRmOS04NTJhOTQzYjdkOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMTcyMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFiODllMTg3MDY4MWU4ZGQ4ZDBmZjZmZDczOWEyNTY5MTgzMWExYmIzM2MzMWViNmNhZjBhZjI1Y2JkNDQ3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uf0nTK2ZoTDTX3V-QU3ua-UgmllAo7CXa_yxs8iRn8Y)
> 
> > Success! Power: 333946.81W. Immer gleich kw mW oder Watt.
> 
> Bei dieser Ausgabe hattest du wohl kW eingestelt?
> 
> Also ich hab auch noch nicht begriffen, was hier das Problem ist...
> 
> Bitte kopiere die im PowerMeter eingestellt URL in deinen Browser und zeig uns, was dann zurückkommt.

![IMG_6870](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/a00295eb-fbab-4215-a3db-7371fbcac318)
![IMG_6869](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/7400cb21-6616-45f2-be48-a4ca8b1e83f2)
![IMG_6868](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/deedc4c2-46ab-41e4-8f4a-c8db67e7eede)

Bitte kopiere die im PowerMeter eingestellt URL in deinen Browser und zeig uns.... Wo ist die URL.

**Comment by Omermann** [comment]
Wenn es jemanden gibt, der aus der Ferne helfen kann. Ich kann die Passwörter geben. (Teamviever)

**Comment by spcqike** [comment]
> Wo ist die URL.

auf deinem 7. Screenshot. 

http://192.168.1.69/emeter/0

**Comment by Omermann** [comment]
{"power":-167.06,"pf":-0.96,"current":0.74,"voltage":234.19,"is_valid":true,"total":334168.0,"total_returned":355814.1}

**Comment by schlimmchen** [comment]
"total" ist die bezogene Energie (kWh), nicht die aktuelle Wirkleistung. Stelle "power" als JSON Pfad ein, dann wird es passen.

**Comment by spcqike** [comment]
Jap. 

Dann ist dein json Pfad falsch. Du fragst „total“ ab, das ist der „Zählerstand“ 

du willst aber „power“

das wird aber vor dem openDTU Update ebenfalls falsch gewesen sein. 

Und immer noch keine Frage:
Warum willst du nur Phase 1 Abfragen?

**Comment by Omermann** [comment]
> "total" ist die bezogene Energie (kWh), nicht die aktuelle Wirkleistung. Stelle "power" als JSON Pfad ein, dann wird es passen.

Ich hab kW gemacht 
![IMG_6871](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/d8cf351b-132d-4066-9bfd-06f22a548138)

**Comment by Omermann** [comment]
> Jap.
> 
> Dann ist dein json Pfad falsch. Du fragst „total“ ab, das ist der „Zählerstand“
> 
> du willst aber „power“
> 
> das wird aber vor dem openDTU Update ebenfalls falsch gewesen sein.
> 
> Und immer noch keine Frage: Warum willst du nur Phase 1 Abfragen?

Ich habe für alle die gleichen Einstellungen vorgenommen.

**Comment by spcqike** [comment]
> Ich hab kW gemacht

nur dass der Shelly keine kW, sondern W liefert 

> Ich habe für alle die gleichen Einstellungen vorgenommen.

also hast du drei openDTUs und drei wechselrichter? Oder hast du nun alle drei Phasen mit einzelnen URLs hinzugefügt?

**Comment by Omermann** [comment]
das wird aber vor dem openDTU Update ebenfalls falsch gewesen sein.
total_power es war Schreibe.
Alles hat ordnungsgemäß funktioniert.
Ich habe schon viele neue Versionen installiert und hatte keine Probleme.

**Comment by Omermann** [comment]
also hast du drei openDTUs und drei wechselrichter? Ein openDTU on battery. Noch ein openDTU aber Shelly nicht verbind.Oder hast du nun alle drei Phasen mit einzelnen URLs hinzugefügt? Ja.
![IMG_6874](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/2265885d-4f99-47c5-9934-b47777bbd40b)
![IMG_6873](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/163d9c00-1c08-418b-8367-504e821af05a)
![IMG_6872](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/79489ae9-cd18-4311-8c93-b7b7bf92f1c2)

**Comment by Omermann** [comment]
![IMG_6875](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/08a51984-fe1d-48d1-b6fd-a6648b2396d1)
Sind diese Einstellungen korrekt? für nulleinspeisung

**Comment by Omermann** [comment]
![IMG_6876](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/62f93e59-c88c-4815-a491-c9e27d9d1843)

**Comment by spcqike** [comment]
> Sind diese Einstellungen korrekt? für nulleinspeisung

nein. Du fragst drei mal die gleiche Phase ab (emeter/0) 

warum hältst du dich nicht einfach ans Wiki und fragst den gesamten Leistungswert ab? 

http://ip/status 

Und als json Pfad

total_power

?

**Comment by Omermann** [comment]
![IMG_6878](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/922635dd-13e5-409f-aed3-b7d32491a714)
![IMG_6877](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/145877362/4aa5052c-7b72-4d78-aa89-20e7458a99ea)

alles scheint in Ordnung zu sein

**Comment by schlimmchen** [comment]
Danke @spcqike.
