### ISSUE TITLE
Dynamic Power Limiter

### ISSUE THREAD

**Issue by rsReitzner** [helgeerbe/OpenDTU-OnBattery#1100]
### Is your feature request related to a problem? Please describe.

kein Problem

### Describe the solution you'd like

Ich habe zwei Wechselrichter mit je 4  Platten auf dem Dach. Den Stromverbrauch sowie Soc und Batteriestatus lese ich mit Mqtt aus. 
Wenn ich Dynamic Power Limiter aktiviere, kann ich nur einen Wechselrichter konfigurieren. Wäre es möglich hier den zweiten hinzuzufügen?

**Comment by schlimmchen** [comment]
Nein, das geht bisher nicht. Das wird aber kommen. Ich vermisse das auch, ich hab Ideen dazu, aber Zeit zu finden ist nicht einfach.

Das wurde auch schon mehrfach angesprochen/gewünscht, z.B. in #230. Ich schließe dieses Issue, weil es kein weiteres dazu braucht.
