### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by helgeerbe** [helgeerbe/OpenDTU-OnBattery#115]

**Comment by helgeerbe** [comment]
- Describe MQTT Messages
- Functional description power limiter
- describe that VeDirect requires cable

**Comment by berni2288** [comment]
When I have time I would like to work on the README & documentation.

Should we rename the `README.md` of the parent project OpenDTU to something like `README-OpenDTU.md`?
It would probably make it easier for us because we would be more independent and avoidmerge conflicts with the parent OpenDTU project.

**Comment by madmartin** [comment]
> Should we rename the `README.md` of the parent project OpenDTU to something like `README-OpenDTU.md`? It would probably make it easier for us because we would be more independent and avoidmerge conflicts with the parent OpenDTU project.

definitely yes.

**Comment by MalteSchm** [comment]
I thought about taking a stab at this (probably over Easter).
IMHO the readme has become too large and should be broken down into individual documents. Can this be done after renaming README.md (to simplify merging)?

I thought about these changes:
- Merge "Features for end users" section with "Extensions to original openDTU" section
- Factor out Dynamic Power Limiter Interface into separate doc
- Merge MQTT information with already existing MQTT document
- Merge "REST-API (/api/verdirectlivedata/status):" into "Web-API Documentation"
- Create Hardware document, move Hardware information there, exend to cover the added peripherals
- Create getting started document, move getting started information there

**Comment by berni2288** [comment]
Jesus, our project is growing and we get a lot of ⭐😅
I'll look into writing proper documentation this week and test how the GIT merging logic behaves when we rename the original README.

**Comment by helgeerbe** [comment]
Beside readme, would be good if we check 
+ the actions, 
+ introduce our own release number
+ refactor System and About Page (keep the links to the original OpenDTU, but address our extensions).

**Comment by helgeerbe** [comment]
Close this, as we moved the doc to the wiki a a living document.
