### ISSUE TITLE
[Request] AC Ladegerät, angestrebter Netzbezug Limit erhöhen

### ISSUE THREAD

**Issue by woollfi** [helgeerbe/OpenDTU-OnBattery#1154]
### Describe the solution you'd like

höheres Limit als -3000 für angestrebten Netzbezug bei AC Ladegerät

**Comment by Solarteur** [comment]
An welches AC-Ladegerät hast du denn gedacht? 

Die bisher möglichen 3000W (an einer Phase) sind schon "sportlich".

**Comment by woollfi** [comment]
Leistung passt schon, ich meinte den angestrebten Netzbezug, der ist bei -3000W begrenzt, gut wäre da kein Limit nach oben, das man mehr variieren kann.

Lg 

Von meinem iPhone gesendet

**Comment by AndreasBoehm** [comment]
@woollfi Könntest du einen Screenshot anhängen der erklärt um welches Eingabefeld es geht? Danke

**Comment by woollfi** [comment]
![0C6B99AB-4566-4297-AC98-A85FF46F2B6A](https://github.com/user-attachments/assets/be2ff3a6-6487-4939-b8ca-8fc742560230)
![F21927B8-BD0F-437D-B43E-20EFC9196F8F](https://github.com/user-attachments/assets/57666bda-2304-4119-a0bc-c23329af8d75)
![B962959F-5B93-4C2B-BBFC-0298BA856C25](https://github.com/user-attachments/assets/5825a04f-f1f2-4ffd-9692-f7fd861e9cba)
![1E1FD98F-2B10-4800-97AC-990903FC816F](https://github.com/user-attachments/assets/ff2352e1-c089-442b-9436-7f83368d11c6)
