### ISSUE TITLE
Pin Mapping über pin_mapping.json wird ignoriert

### ISSUE THREAD

**Issue by khasselt** [helgeerbe/OpenDTU-OnBattery#116]
### What happened?

Ich habe das File pin_mapping.json mit anderen Ports gefüllt als 21 und 22
Wenn diese beiden verwendet werden, geht es wenn ich aber andere eingebe führt dazu das es schlicht nicht mehr funktioniert
Sprich hier fehlt wohl im code noch eine Weiche das auf die anderen Ports geschaltet wird

### To Reproduce Bug

pin_mapping.json hochladen mit anderen Ports als 21/22 konfiguriert, an diese Ports anstecken.
Geht nicht

### Expected Behavior

Verwendung der angegeben Ports 

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

Aktuelle

**Comment by helgeerbe** [comment]
Ich schaue mir das mal an. Welche Ports wolltest du den verwenden?

**Comment by khasselt** [comment]
1 & 3. das sind die Ports für mein esp32 auf denen das reference Board die hat

**Comment by helgeerbe** [comment]
Auch wenn es drauf steht. Dass sind die RX/TX pins für das flashen. Die solltest du nicht verwenden.

The GPIO1 (TX0) and GPIO3 (RX0) pins are used to communicate with the computer in UART via USB. If you use them, you will not be able to upload programs to the board or use the serial monitor via the USB port. They can be useful for programming the board without a USB but with an external programmer instead. Fortunately, there are other UART interfaces available.

Schau mal hier:  https://www.upesy.com/blogs/tutorials/esp32-pinout-reference-gpio-pins-ultimate-guide
Da gibt es auch eine Tabelle der Pins. Am besten nimmst du die, die nicht anderweitig belegt sind.

**Comment by khasselt** [comment]
Und denkst du deswegen gehen sie nicht? Wie gesagt das sind die Pins die das referenzboard für Display nutzt

**Comment by helgeerbe** [comment]
Kann ich nicht sagen, habe ich nicht versucht. Ich kann am WE nur testen, ob die gesetzen Pins wirklich für die Serielle Schnittstelle verwendet werden. Ob die Schnittstelle damit klar kommt kann ich nicht ausprobieren, da bei mir die OpenDTU Pins schon hart verlötet sind.

**Comment by khasselt** [comment]
Das ist doch schonmal was :)

**Comment by helgeerbe** [comment]
GPIO 1 : Sends the ESP32 boot logs via the UART
GPIO 3 : 3.3V voltage at boot time

Solltest du definitiv nicht benutzen. GPIO 3 ist RX hier sollten Signale ankommen und keine Spannung anliegen.

**Comment by helgeerbe** [comment]
So, ich habe mir gerade mal das setzen der Pin ausgeben lassen. Das funktioniert korrekt. Allerdings bricht natürlich das logging über usb ab, wenn ich die PINS 1 und 3 verwende. Ich würde also sagen, alles korrekt hier.
