### ISSUE TITLE
"Use Battery At Night" must move

### ISSUE THREAD

**Issue by schlimmchen** [helgeerbe/OpenDTU-OnBattery#1169]
### Describe the solution you'd like

Since #1126 (more specifically #1158 and #1160 by @AndreasBoehm) the "start a battery discharge cycle at night even if the battery is only partially charged" option is not dependent on knowing the solar power. This option shall hence be available globally, i.e., also for users without VE.Direct enabled. It shall NOT be available if the inverter is solar-powered. Move the respective switch to the "Inverter" section of the DPL settings web UI.

**Comment by AndreasBoehm** [comment]
Good idea, i will take care of this tomorrow
