### ISSUE TITLE
[Request] add feature to charge akku with max AC power

### ISSUE THREAD

**Issue by onehub278** [helgeerbe/OpenDTU-OnBattery#1247]
### Is your feature request related to a problem? Please describe.

it would be nice to have a feature to charge akku with max AC power (Huawei R4850G2), when energy costs are very low

### Describe the solution you'd like

for example: add a max charging power field in watts and overrule auto power charger limiter via MQTT

### Describe alternatives you've considered

maybe i can do it manually under "AC Charger config" -> Disable "Auto power charger limiter" -> using "emergency charging" 

### Additional context

iam aWATTAr consumer and it is possible to get negative energycosts mostly at weekend, but also get very high energycosts at early morning or at afternoon

**Comment by gitisgreat2023** [comment]
See [here](https://github.com/MalteSchm/OpenDTU-OnBattery-Controller).

**Comment by onehub278** [comment]
it seems all necessary commands are already implemented via API or MQTT:
https://opendtu-onbattery.net/firmware/web_api/#list-of-urls (/api/limit/config)
https://opendtu-onbattery.net/firmware/mqtt_topics/#inverter-total-topics (solar/powerlimiter/cmd/mode)

please close this request

thx

**Comment by schlimmchen** [comment]
Okay, thanks for your feedback! Happy to see that you found a working solution :muscle:
