### ISSUE TITLE
[Request] add LAN support for OpenDTU Fusion Board

### ISSUE THREAD

**Issue by onehub278** [helgeerbe/OpenDTU-OnBattery#1251]
### Is your feature request related to a problem? Please describe.

to get a better network performance (latency, PoE), it would be nice to support also LAN interface from OpenDTU Fusion with Fusion PoE NIC

### Describe the solution you'd like

option to choice WLAN- or LAN-Interface

### Describe alternatives you've considered

now iam using WLAN

**Comment by spcqike** [comment]
See https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1231
