### ISSUE TITLE
[Request] Access serial console for Fusion Board

### ISSUE THREAD

**Issue by onehub278** [helgeerbe/OpenDTU-OnBattery#1254]
### Is your feature request related to a problem? Please describe.

It seems access to serial console for Fusionboard ist not possible
Serial output stops at:
E (348) esp_core_dump_flash: No core dump partition found!

### Describe the solution you'd like

please add same feature as described here:

https://opendtu-onbattery.net/firmware/howto/serial_console/

### Additional context

tested with several USB-Cables and other boards:
opendtu-battery-on-FusionBoard stops output
![opendtu-battery-on-FusionBoard](https://github.com/user-attachments/assets/48b2ba63-ca4d-4926-a579-10e0ba97595a)
espresense-on-ESP32-S3-DevKitC-1 output is workng fine
![espresense-on-ESP32-S3-DevKitC-1](https://github.com/user-attachments/assets/0a02cbe9-2b1a-4710-83ed-4feb7be317ef)
opendtu-battery-on-ESP32-NodeMCU-DevKitC output is workng fine
![opendtu-battery-on-ESP32-NodeMCU-DevKitC](https://github.com/user-attachments/assets/45d3e5c4-0994-4c1b-9f7e-4ea0cecec920)

**Comment by AndreasBoehm** [comment]
Which exact build did you flash on your fusion?
This information should be available on the system info page of the dtu.

**Comment by onehub278** [comment]
> Which exact build did you flash on your fusion? This information should be available on the system info page of the dtu.

![grafik](https://github.com/user-attachments/assets/2a8cc540-84d9-4ad6-89de-3d7b029136f4)

**Comment by AndreasBoehm** [comment]
I think you should use the esp32s3_usb build instead

**Comment by schlimmchen** [comment]
Yes, as is [documented)(https://opendtu-onbattery.net/firmware/#overview-of-firmware-variants).

@onehub278 You may use the `esp32s3` variant (without `_usb`), but you can't expect to see message output on the USB port in that case. The messages will appear on the UART header instead.

**Comment by haegar33** [comment]
I got a openDTU-development branch in Platformio on Visual Code. There an enviroment **openfusionenv2** is available. Is this outdated or a new feature?

**Comment by schlimmchen** [comment]
Neither. It's the same as `generic_esp32s3_usb`, except that it defines default values for some pins, which you can as well set using the recommended method: uploading a `pin_mapping.json`.
