### ISSUE TITLE
[BUG] CMT2300A not working when using opendtufusionv2 with W5500 enabled

### ISSUE THREAD

**Issue by vaterlangen** [helgeerbe/OpenDTU-OnBattery#1257]
### What happened?

When I select the profile `OpenDTU Fusion v2 with CMT2300A and W5500 ethernet` on my OpenDTU Fusion v2 with PoE Shield, the CMT2300A is not detected and no communication to my inverter is possible (Ethernet is working perfectly fine). Seems like OpenDTU-OnBattery assumes, it should use the NRF24 (see screenshots)

When using the profile `OpenDTU Fusion v2 with CMT2300A and NRF24` (**without W5500**) on the same FW build, CMT3200A is working as expected. 

### To Reproduce Bug

Switch to profile `OpenDTU Fusion v2 with CMT2300A and W5500 ethernet` on a OpenDTU Fusion v2 with PoE Shield

### Expected Behavior

CMT2300A is usable

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

a6e7007

### Anything else?

Device Manager shows CMT2300A enabled 
![grafik](https://github.com/user-attachments/assets/764e4162-ef17-41b3-8a93-700db0aea23f)

DTU Settings show NRF24
![grafik](https://github.com/user-attachments/assets/4c7611b3-d3ed-4b7d-a751-7c839c2097fc)

System Info also shows NRF24
![grafik](https://github.com/user-attachments/assets/a86a76af-0b94-4a4c-8af5-0e4e5f885dda)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported

**Comment by skippermeister** [comment]
@vaterlangen 
Die Chips ESP32 und ESP32S3 habennur 2 freie SPI Ports.
NRF24 + CMt + W5500 funktioniert nicht zusammen.
Wenn Du CMT + W5500 nutzen möchtest, dann musst im Pinmapping die Pins für das NRF24 Modul alle auf -1  setzen. Dann wird das RF Modul nicht initialisiert und der SPI Port wird frei.

**Comment by vaterlangen** [comment]
@skippermeister  Danke für den Hinweis - hat geklappt!

Updated mapping for W5500 modes accordingly - see #1259

**Comment by schlimmchen** [comment]
Am I assuming correctly that you built for the opendtufusionv2 environment?

**Comment by vaterlangen** [comment]
Correct
