### ISSUE TITLE
[Request] Add support for multiple inverters for power limiter

### ISSUE THREAD

**Issue by remigauthier** [helgeerbe/OpenDTU-OnBattery#1295]
### Is your feature request related to a problem? Please describe.

It is not currently possible to limit power for multiple inverters

### Describe the solution you'd like

Two possibilities I can think off :
- limit all inverters at the same percentage (using the sum for each instance to calculate if the total acheive the limit)
- shut down inverter one after the other till the limit is reached

**Comment by remigauthier** [comment]
duplicate of https://github.com/helgeerbe/OpenDTU-OnBattery/issues/230

**Comment by spcqike** [comment]
See https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1216
