### ISSUE TITLE
[Gelöst] mit HUAWEI Relais hängt meine DTU unregelmäßig auf 

### ISSUE THREAD

**Issue by Manos1966** [helgeerbe/OpenDTU-OnBattery#1373]
### What happened?

Es ist bereits drei Mal passiert seitdem ich Release 2024.10.22 installiert habe, deswegen melde ich es, falls noch andere es bemerkt haben.
Ich habe nichts geändert, außer das neue Release 2024.10.22 zu installieren.

Mit circa 3-4 Tage Abstand, kann ich auf die OpenDTU nicht zugreifen.
Nur das Entfernen der Stromzufuhr hilft.

NRF24+, HUAWEI, CANbus (Pylontech), OpenDTU Uhrzeit für geplanten Neustart 12:00, Relais fuer HUAWEI Power

Ich versuche mehr Infos zu sammeln.

![01](https://github.com/user-attachments/assets/0444c378-97f7-419d-9030-247e7494f91b)
![02](https://github.com/user-attachments/assets/f3d43525-d56e-4a4e-87a6-86416cdbb502)
![03](https://github.com/user-attachments/assets/40d79ba0-4bfd-4bda-b260-c2846ecbe4da)
![04](https://github.com/user-attachments/assets/7ee2fcd5-62c1-4eca-ba32-c7ca5e79691f)
![05](https://github.com/user-attachments/assets/a671ab09-1ae2-42e9-b1a9-1d673c83a1ee)
![06](https://github.com/user-attachments/assets/09929483-d6a5-4542-b319-827a99d9493f)

### To Reproduce Bug

Nicht möglich, ich versuche mehr Infos zu sammeln

### Expected Behavior

Bei der vorherigen Version ist es nie passiert.
Ich habe auch nichts an der Hardware oder Einstellungen geaendert.

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU-OnBattery?

2024.10.22

### What firmware variant (PIO Environment)?

generic_esp32s3_usb

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by Manos1966** [comment]
UPDATE: Es koennte Sein, dass @knoppers1 den moeglichen Grund gefunden hat
Das Problem hatte ich aber nicht mit dem vorherigen Release, daher bin ich nicht sicher, dass es daran liegt (das Relais geht mehrmals am Tag ohne Problem ein und aus).
Es ist aber eine Moeglichkeit die ich pruefen muss. 


> Moin, die Wahl des Relais ist nicht optimal, auch wenn es für den Anfang gut funktioniert....! Es ist ein mechanisches Relai was auch verschleissen kann, der Anlaufstrom der Spule zieht kurzzeitig die Boardpannung runter. Und es ist wieder ein separates Teil, das in das Gehäuse der Steuerung passen muss. Es gibt besseres..... Halbleiterrelai (SSR.) Aus einzelnen wenigen Bauteilen lässt sich ein Ersatz nachbauen, das kompakter und vor allem nicht zu verschleissen ist. Oben drauf, lassen sich die drei Widerstände, Led, und das Relai (AQY212) selbst auf die Lochrasterplatine auf kleinstem Raum intergrieren. [AQY212GH.PDF](https://github.com/user-attachments/files/17634459/AQY212GH.PDF) Anbei Datasheet als PDF, falls sich einer näher interessiert, sowie ein Stromnlaufplan passend dazu. Viel Erfolg beim Nachbauen.
> 
> ![solidState](https://private-user-images.githubusercontent.com/128924216/383194428-a578e839-e9df-49af-879d-91e3c1344c05.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjMyNjIsIm5iZiI6MTczMDgyMjk2MiwicGF0aCI6Ii8xMjg5MjQyMTYvMzgzMTk0NDI4LWE1NzhlODM5LWU5ZGYtNDlhZi04NzlkLTkxZTNjMTM0NGMwNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNjA5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGVkZTBkODBjYTBjM2FjNjI5MmEzNDMzNzFlZWY5Y2Y4NmEzYzg0M2UwZWZhMTU2Yjc1NzVkNzNlN2EwMGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3-55TTREY9YJSuQjrPrBsSoaWq8WhsXPX1snkt4pXsI)

**Comment by knopers1** [comment]
@Manos1966 
bis jetzt habe ich mit der letzten Release überhaupt keine Probleme!
Das, was Du versuchen kannst ist: 

**1**: das Steckernetzteil selbst, ich gehe davon aus, dass Du den ESP32-s3 über die USB-C Schnittstelle angeschlossen hast- stimmt das so? **Welche Spannung kannst Du am GPIO 5V messen?** Ein stabiles Netzteil ist die Vorraussetzung, dass dein ESP stabil funktioniert. Gerade jetzt, wo auch die Relais mit der Spule zum Einsatz gekommen sind. Ein schwaches, nicht sonderlich stabiles Netzeil taugt nur bedingt etwas , wenn man damit ein Handy Akku aufladen möchte. Dort ist die Stabilität nicht wichtig, da ein Akku auch mit unsaubarer DC Spannung den Akku voll bekommen kann. Du brauchst etwas gutes! Schau bei Amazon nach, für ca. 8€ gibt es einige namhafte mit 20 Watt Leistung. Das mag auch viel oder zu viel sein, aber ein starkes Netzteil geht einfach nicht so schnell in die Knie, wenn es kurzzeitig stark belastet wird.

**2**: Kondensator: Um die Spannung zusätzlich zu stabilisieren, kannst Du am 5V GPIO gegen die GND einen Folienkondensator einbauen. Hast Du einen bereits verbaut? 100nF (Keramik) und 20µF oder mehr (Elko). Schau zu, dass du die Elkos auch für passende Spannung bekommst (5-15V). Der Keramik gibt die Spannung sehr zeitig ab, die dicke Folie eher spät, dafür aber hat das Teil eine ordentliche Ladung um die abgesackte Spannung nach oben zu stabilisieren. 

**3**: Das Relai vorerst abklemmen und beobachten. Die alten Relai´s mit der Spule sind nicht optimal, Deshalb habe ich dort die Schaltung zur Verfügung gestellt, um eben die Probleme mit dem Verschleiss oder der Spannungsversorgung zu minimieren. So auf die schnelle als fertiges Board? Da müsste ich suchen... Schau nach einem Optokoppler! 

Eventuell das da:
![1](https://github.com/user-attachments/assets/8006e69e-486c-4dcc-9e54-4c597b1d3035)

![2](https://github.com/user-attachments/assets/6d54a62a-8248-4667-b3b6-af0d82d1405f)

Viel Erfolg!

**Comment by Manos1966** [comment]
Danke @knopers1 

ich habe ein 5V 3A Netzteil angeschlossen. Liefert stabil 5,1V und 0,3A
ABER, ich werde gucken was passiert, wenn die Relais sich ein/aus schalten 
(ich habe vergessen zu erwähnen, ich habe zwei, eins für die 48V HUAWEI und eins für die 12V Lüfter 😁)
![5V Netzteil a](https://github.com/user-attachments/assets/423227f3-8f42-449c-83ef-0bbb59941d7c)
![5V Netzteil b](https://github.com/user-attachments/assets/09b44104-fa8f-475a-ab5d-c2584b3f7f15)

Die Idee mit dem ELKO ist gut, ich habe genug davon, von  20µF bis 700µF
Ich habe noch keinen, weil ich sicher war, dass der ESP32-S3 mit Micro-C Stecker viel mehr Strom verträgt, als die alten...

Danke für die Suche ❤️ ich werde mir ein paar S.S.R. bestellen (und im Wiki addieren)

Die vierte Option wäre zurück auf die vorletzte Firmware Version zu gehen und sehen ob das Problem wieder eintritt.

**Comment by knopers1** [comment]
@Manos1966 
so einfach ist es nicht, dein Messinstrument ist dazu nicht geeignet weil vor allem viel zu träge!
Ein Osziloskop müsstest Du schon haben, ein Taskkopf als Trigger... dann würdest du etwas sehen.
Dein Power Supply macht einen wertigen Eindruckt, trotzdem kann er auch defekt sein. Nichts hält ewig...
Dir bleibt nichts viel über, als dit Teile nacheinander austauschen! Hast Du die Spannung am GPIO +5V gemessen? 
Ich konnte bei mir gerade 4,4V messen. Allerdings habe ich die Spannung meines Netzteils nicht überprüft.

Ich würde erst bei dem Relai anfangen, das SSR dürfte keinen Pik beim Ein/Schalten erzeugen. Danach die Elkos und Probelauf...

**Comment by Manos1966** [comment]
ein Kaleidoskop ? 😝 
das sind Aufgaben weit ueber meine Gehaltsklasse @knopers1 😆 

Mein Punkt (=Hoffnung) war, da das Netzteil mit nur 10% Prozent seiner maximalen Leistung läuft, die Stromversorgung stabil sein sollte.

Ich werde die Spannung am GPIO messen.

Ich werde auch das zweite 3,3V Relais (Luefter) abschalten. Braucht man nicht wenn die HUAWEI <1000W produziert.

Wichtig ist auch, dass du keine Probleme mit der 2024.10.22 hast. Wir haben die gleiche Hardware (ausser CANbus?).

S.S.R. bestelle ich heute.

So oder so, so lange ich den Fehler nicht reproduzieren kann, ist alles schwierig.
Danke fuer deine Hilfe!

**Comment by knopers1** [comment]
Hast Du ebenfalls das Relai eingebaut?
![IMG_0912](https://github.com/user-attachments/assets/e432ecac-57c1-498b-b17e-f1cb17401021)

Ich habe mich dort mit dem Jumper schnell verrant, und hatte den anders als im Bild gesteckt. 
Folgendes ist passiert! Das Relai hat angezogen, ist aber gleich wieder abgefallen. Das hat er mehrmalls in der Minute gemacht.
Mir ist es leider nicht gleich aufgefallen, da die Steuerung in der Garage ist. Bis ich den Fehler entdeckt habe, hatte mein Shelly zwei Mal wegen Überlast >1000 Watt abgeschaltet! 
Das Relai hängt bei mir an 3.3V. 

Wenn das Relai anzieht, wird die AC Seite durch des Netzteils ordentlich belastet. Dies hatte ich auch an meiner Beleuchtung in der Garage gesehen. (kurzes flackern der Lampe). Die AC Spitze hat wieder einen Einfluss auf die Netzteil, die dir die 5V für den ESP32 aufbereiten.

**Comment by Manos1966** [comment]
Guten Morgen @knopers1 
ich nutze noch das andere Relais (x2 🙈 ) ohne High/Low Jumper.
Das Problem hatte ich schon am Anfang (Wackel-Kontakt), trotzdem blieb meine OpenDTU stabil (aber damals war nur ein Relais (nicht zwei) angeschlossen!

Meine Shelly schaltet den 230V Eingang der HUAWEI, die auf Minimum programmiert ist (3Ax50V=150W) und auf meine 36A 230V Leitung haengt, daher haette die Shelly nichts bemerkt.
Deswegen, vielen Dank fuer deine Erklaerung ❤️ 

Also, als erstes, entferne ich das Relais fuer die Luefter (nicht gebraucht).
Zweites, ELKO anschließen (Was ist lieber? ELKO direkt auf dem Relais, oder am ESP32)?
Drittens, die S.S.R. Relais installieren.
Wiki habe ich schon ergaenzt...

![Relais 3 3V - C](https://github.com/user-attachments/assets/e55130d2-6a79-4ee8-b5ed-6eb45c79a465)

**Comment by knopers1** [comment]
@Manos1966 
ja, den Shelly Plug habe ich auf der AC Seite des Huaweis eingebaut und den Strom auf 1000 Watt begrenzt.
Trotzdem haut es richtig rein, sobald das Relai angezogen wird.

Den Elko kannst Du einbauen wo du möchtest, da der VCC und GND des Relai´s parallel zum ESP32 verdrahtet ist. 
Demnach spielt es keine Rolle, wo du das Teil einbaust. 
Das SSR Relai ist da schon gut aufgehoben, da keine großen Ströme zumindest auf das 5V Netzteil des ESP´s beim Zuschalten da sind.

**Comment by knopers1** [comment]
die Idee mit dem Shelly auf der AC-Seite des Huaweis ist echt Klasse.
Aus dem ioBroker kann ich den Shelly über einen Script erst dann einschalten, wenn überhaupt ein Überschuss zu erwarten ist.
Heute ist wohl hier vor Ort ziemlich dunkel und nass, der Shelly bleibt heute automatisch aus. 

![1](https://github.com/user-attachments/assets/a48a6038-d6f1-44c2-a34c-4ffd0d35b6fd)

![2](https://github.com/user-attachments/assets/dc533d1c-8ab4-43b7-af06-66bc026d2a65)
![3](https://github.com/user-attachments/assets/fab52d1d-834c-4386-8fdf-52a1e0983c8c)

Deshalb an der Stelle risen Dank, es ist eine geile und sinvoller Ergänzung für die Steuerung des Huaweis.

**Comment by knopers1** [comment]
@Solarteur 
Du hast ja dort einen Fehlker, da Du den Slot Detect (Kabel ws,sw) gegen GND des Netzteils schalten muss und nicht untereinander. 
Des Weitern fehlt ewentuell die Anzeige, dass dein Power Gpio An/Aus ist?, die ist in der unteren Schaltung da. 
Ein Pulldown Widerstand ist auch nicht da, wenn dein Power Gpio erneut wieder Low ist, solltest Du den auch definiert gegen die GND ziehen, ein R10K ist dabei sehr hilfreich. 
![3](https://github.com/user-attachments/assets/5e87ee07-f426-4807-8a08-43b5fb943bc3)

![2](https://github.com/user-attachments/assets/3781a577-2e00-4a0e-88ac-50fc53c8b492)

**Comment by Manos1966** [comment]
> Ein Pulldown Widerstand fehlt noch, wenn dein Power Gpio erneut wieder Low ist, solltest Du den auch definiert gegen die GND ziehen, ein R10K ist dabei sehr hilfreich. (siehe die untere Schaltung)

Ist das Deutsch? 🙈 🤣🤣🤣🤣🤣
... ich bin froh ich kann etwas fertiges aus China bestellen 😄 

Spass bei Seite, vielen Dank @knopers1 und @Solarteur fuer die Vorschlage. 
Dank Euch habe ich (wahrscheinlich) das Problem gefunden und sogar die moegliche Loesung. Noch wichtiger, ich kann sicher sein, das Problem liegt an meiner HW und nicht an der OpenDTU SW 💯 

> Edit: Vielleicht sollte dieses "Issue" nach "Discussions" verschoben werden.

Einverstanden! @schlimmchen Bernhard, ist eine Verschiebung moeglich?

**Comment by Solarteur** [comment]
@knopers1 

Du hast recht, in meiner Skizze oben war ein Fehler - hier die Korrektur:

![Slot_detect_Optokppler](https://github.com/user-attachments/assets/c395ef6c-a354-40a9-8df1-870aea9d37bf)

Der Ansteuerteil für die LED des Optokopplers ist bei mir genau so in Betrieb.

Fall 1:
Der ESP32 GPIO "Power" ist "High", wenn das Huawei-Netzteil **nicht aktiviert** sein soll. 
Die Anode und die Kathode der LED liegen auf + 3,3 V --> der Phototransistor des OK wird nicht angesteuert.

Fall 2:
Der ESP32 GPIO "Power" ist "Low", wenn das Huawei-Netzteil **aktiviert** sein soll. 
Die Anode der LED liegt auf + 3,3 V und die Kathode auf 0 V --> der Phototransistor des OK wird angesteuert und das Huawei-Netzteil ist aktiviert.
