### ISSUE TITLE
[Request] Additional PowerLimiter strategy: Empty battery at night

### ISSUE THREAD

**Issue by helgeerbe** [helgeerbe/OpenDTU-OnBattery#139]
### Is your feature request related to a problem? Please describe.

Battery was yesterday nearly full. Today my solar system produces more energy, than I can consume. So MPPT goes into absorption and reduces the charge current.

Actual strategy is to charge battery until start threshold is reached and then empty battery. 
This is fine as long you don't have additional unbuffered solar systems. 

### Describe the solution you'd like

I would like to have  a new strategy.

If system is in state solarPassthrough and panelPower drops below lowerPowerLimit the inverter shouldn't be switched off. Instead the powerLimiter should switch in state normal_operations. 

So when the sun is not shining, battery should be used and empty the battery over night. Each morning maximum battery capacity is available to store unconsumable energy.

This code be realized as an option if solar passthrough is enabled.

**Comment by berni2288** [comment]
Hmm, you can just set the start threshold lower.

Example: 

- Stop threshold:: 20%
- Start threshold. 25%

Then you will probably not have any problems.

What you are suggesting is quite difficult because there can be a short sun burst and then suddenly only 10% panel output again.

**Comment by berni2288** [comment]
Woops, new record for 2023: 4 kWh in one day. My batterie also got full it seems :smile::

![image](https://user-images.githubusercontent.com/1029328/225690970-03d804ea-d7c8-4711-b590-5fe6842e7b9b.png)

**Comment by helgeerbe** [comment]
This happened to me, too. But I just have an 2kW Battery. So I would prefer to keep the battery as empty as possible.

I just implemented it in my branch and will test it tomorrow. 

If state is solarPassThrough and PanelPower drops below lowerPowerLimit it will drain the battery until stopThreshold is reached. When inverter restarts it will start with solarPassTrhough.

**Comment by berni2288** [comment]
I understand, losing energy is not good.

Could you make this feature configurable? I have the fear that when it's a cloudy day that it would stop and start the inverter very often.
The load-corrected voltage value is not very relieable and can jump around when there are bigger sudden power limit changes. This is quite hard to test. It might work good for some time and then suddenly get into a stop/start loop.

**Comment by helgeerbe** [comment]
It already is,

![image](https://user-images.githubusercontent.com/59169507/225721704-0bcf6288-24f8-463b-9663-41ba7553d4f4.png)

**Comment by helgeerbe** [comment]
To understand your request.

You want one upper limit during the day and another one for the night?  What is the benefit?

Even at night, maximum will be the upper power limit. But normally it should follow your power import from the grid.

**Comment by Adminius** [comment]
The difference is the cell voltage and voltage drop at hiher current. The voltage drops less at lower power. In most cases this can be longer battery usage.
Example: cells are at about 3.1V. And the voltage drops at 100W limit only 0.1V and 0.3V at 600W.
BMS will shutdown at 2.7V.
With a 600W we are near the BMS undervoltage, because of 3.1-0.3=2.8V. If one cell of the pack goes below, BMS turns off. And the voltage recovers an stays at around 2.9V.

Now we are limiting to 100W, 3.1-0.1=3.0V, it is a lot until under voltage protection and you can use your battery much longer = more Wh usable before BMS turns off.

It is not only day/night, it is in general: the upper limit without solar production (Victron Production Power < upper limit) should be less then 100W in my example.

**Comment by helgeerbe** [comment]
I See your point.
I would propose to use upper and lower power limit, when inverter is on battery and to add a new upper power limit for solar pass through. Power above this limit will load the battery.

**Comment by helgeerbe** [comment]
Put upper solar passthrough limit in issue #142
