### ISSUE TITLE
Neue Version (selbst kompiliert) per OTA einspielen bleibt hängen

### ISSUE THREAD

**Issue by IngoEF** [helgeerbe/OpenDTU-OnBattery#216]
### What happened?

Das Verhalten ist nun das zweite Mal dasselbe und persistiert offenbar:
neueste Firmware in PlatformIO (VS, vorher ge"cleant") kompiliert und OTA versucht.
Blieb wieder bei 35% hängen und es passierte nichts weiter.
Neustart per UI angeschubst und den Hinweis auf Bugreport gelesen.
Auch Hart-Reset durch vom Strom trennen ändert nichts, das Ergebnis im OTA bleibt bestehen.
Deshalb nun dieser Bericht.
Auch Holen der neuesten "opendtu-onbattery-generic.bin" und Einspielen via OTA bleibt an derselben Stelle hängen.
Mir bleibt nichts anderes übrig, als den ESP32 komplett zu löschen und per VS neu zu flashen.
Das ist doch bestimmt nicht Sinn des OTA.

### To Reproduce Bug

Try to flash new version via OTA stucks at 35%.

### Expected Behavior

Working firmware update over OTA

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

83b42a3

### Relevant log/trace output

```Shell
nothing to find
```

**Comment by IngoEF** [comment]
Seems to be wrong branch

**Comment by IngoEF** [comment]
Closing here was in the wrong branch (sorry)

**Comment by helgeerbe** [comment]
Ich kenne das Problem, und es betrifft auch die original openDTU.  Aber ich kenne leider noch nicht den Grund. 
Im allgemeinen hilft ein reboot des ESPs. Wenn du zufällig ein Log File (serial nicht die Web Konsole) hast, wäre ich sehr daran interessiert.

**Comment by IngoEF** [comment]
Im Vater-Branch fühlte sich niemand durch das Problem auch nur ein bisschen berührt.
Im Gegenteil, man verwies mich auf "OnBattery".
Klar versuche ich zu helfen. Mal sehen, ob ich eine Version zurückgehen kann, um das dann nachzustellen.
Im Moment läuft  hier zwar ein BKW mit Einspeisung, aber ohne Regelung. Alles was ich im Moment hier mit OpenDTU(-OnBattery) mache ist reiner Spiel-/Testbetrieb, 
Beim vorletzten Mal meine ich aber, in der seriellen Konsole genau keinen Hinweis auf Steckenbleiben der Aktualisierung gesehen zu haben.

**Comment by IngoEF** [comment]
Hab's jetzt nochmal mit meinem zweiten ESP32 gemacht.
Ergebnis:
bei 35% bleibt OTA hängen und null Konsolenausgabe.
Tut mit leid.
Wenn ich helfen kann, mache ich es gern, brauche dann aber nähere Durchführungsangaben

**Comment by helgeerbe** [comment]
Da bei mir OTA funktioniert, ist das sehr schwierig für mich den Fehler nachzustellen. Der Git-Hash, den du angegeben hast, is von letzter Woche. Wie sieht es mit einer aktuellen Version aus? Funktioniert da OTA bei dir. 

Wie sieht Info-System aus?

![image](https://user-images.githubusercontent.com/59169507/235779964-8ad7d1d7-95b8-4a04-9bc7-c56d21a6a59e.png)

**Comment by IngoEF** [comment]
Nach jetzt nochmaligem git pull/PIO-Clean/-Compile/-Upload ist jetzt die Version 569edbe aktiv

Info/System sieht so aus:
![grafik](https://user-images.githubusercontent.com/26598336/235797919-bc92bd3a-839c-4e3c-9bb6-685cf5204a6a.png)

ein neuer OTA-Versuch:
![grafik](https://user-images.githubusercontent.com/26598336/235798706-3d4f0953-a525-4394-bdab-473f98b1edfa.png)

**Comment by MalteSchm** [comment]
Das hilft zwar nicht viel aber ich benutze OTA dauernd.
Geht

**Comment by helgeerbe** [comment]
Welchen Browser nutzt du, bzw. unter welchem Betriebssystem?
Ich kann es nicht reproduzieren. OTA geht eigentlich immer.

**Comment by IngoEF** [comment]
Browser: fast ausschließlich FireFox.
Eben kommt mir der Gedanke, dass ggf. die Abschottung des IoT-WiFi-Netzes -ausgehend- gegen mein normales Home-LAN der Grund für's Steckenbleiben sein könnte. 
Nachdem nun mein Notebook im IoT-Netzwerk hängt, funktioniert OTA.
Tut mir leid wegen des Aufrisses. Kann ja keiner ahnen, dass der Update-Prozess offensichtlich von ausgehemden Verbindungen zur Quelle abhängig ist; das war an abfragenden / nicht beantwortete Paketen aus dem IoT-Netz im Router Richtung meines Notebooks zu erkennen.

**Comment by helgeerbe** [comment]
Aber gut zu lesen, dass es jetzt geht

**Comment by jubie25** [comment]
Möchte den Thread fortführen, denn all das hilft bei mir auch nichts. Benutze das fertige opendtu-generic.bin File und will von 23.6.9 auf 23.6.26 updaten. Das Update begann auf einem Laptop außerhalb des Netzes (VPN geroutet) und lief durch bis 90+x%, blieb dann stehen. Bin direkt in das Netz rein und habe dort nochmal angestoßen. Lief bis 34%. Firefox gegen Edge und Chome getauscht, läuft bis 6%. Mehrfache Reboots über die Weboberfläche. Die Software scheint normal zu funktionieren, aber Updates sind nicht mehr möglich.
Irgendwie scheinen sich die hocgeladenen Fragmente im Speicher verkeilt zu haben. Wie kriege ich das wieder frei? 
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/72253640/6f682e95-a47b-46b9-8edb-9e14029f9143)
Anders gefragt: kann ich den ESP32 auch mit der USB/seriellen Schnittstelle updaten? Oder die Fragmente freiräumen?
OTAs sind ansonsten kein Thema, stoße erstmalig auf so ein Problem.

**Comment by IngoEF** [comment]
Also zunächstmal ist es so gewesen, dass die Lösung für funktionierendes OTA die Netzwerklokalisierung beider Teilnehmer (also der openDTU und des Web-Clients mit der GUI-Anzeige in ein und demselben Netzsegment sein musste, damit meine ich im gleichen Subnetz.
Die Frage bzgl. des Updates per USB kann ich mit klarem "ja" beantworten. Es funktioniert mithilfe verschiedener Tools, die alle im Readme.md ab [hier](https://github.com/helgeerbe/OpenDTU-OnBattery#flashing-and-starting-up) ausfürlich beschrieben sind. 
Vor dem Flashen sollte möglichst gelöscht werden, dafür hat sich "esptool.py erase_flash" bei mir gut bewährt.

**Comment by spcqike** [comment]
Weden hier OTA und das Update über das Web Interface in einen Topf geworfen? Für mich sind das zwei verschiedene Sachen. 

OTA im gleichen subnet, macht Sinn. 

Das update per web interface ist davon aber unberührt. Zumindest dachte ich das bisher.

**Comment by jubie25** [comment]
OTA ist schlicht ein Überbegriff. Welche Unterscheidungen machst du hier, in technischer Hinsicht im Allgemeinen und in der OpenFatU Firmware im Speziellen?
--
mobil gesendet

28.06.2023 18:04:55 spcqike ***@***.***>:

**Comment by helgeerbe** [comment]
> Anders gefragt: kann ich den ESP32 auch mit der USB/seriellen Schnittstelle updaten? Oder die Fragmente freiräumen?
> OTAs sind ansonsten kein Thema, stoße erstmalig auf so ein Problem.

Ja klar, über usb sollte immer gehen.
