### ISSUE TITLE
[Request] Ladereglerdaten über API anzeigen

### ISSUE THREAD

**Issue by eeprom23** [helgeerbe/OpenDTU-OnBattery#231]
### Is your feature request related to a problem? Please describe.

Hallo, ist es möglich die Ladereglerdaten über vedirect über das api auszulesen ?

### Describe the solution you'd like

ich bekomme sie nicht angezeigt. kann mir einer sagen wo mein Fehler liegt ?

**Comment by helgeerbe** [comment]
Meintest du den Rest Call? http://openDTU/api/vedirectlivedata/status

Oder MQTT?

**Comment by eeprom23** [comment]
Meinte hier http://opendtu/api/livedata/status

**Comment by helgeerbe** [comment]
Da bekommst du nur die Inverter-Daten. Victron livedata hat seine eigne API

**Comment by helgeerbe** [comment]
Ist schon implementiert.
