### ISSUE TITLE
[Request] Victron Batterie Temperatur 

### ISSUE THREAD

**Issue by thorstenlutz** [helgeerbe/OpenDTU-OnBattery#235]
### Is your feature request related to a problem? Please describe.

Hallo,

gibt es die Möglichkeit, beim Victron Smartsolar auch neben Spannung und Strom auch die Batterie Temperatur ausgeben zu lassen?

### Describe the solution you'd like

Im Ve. Direct Protokoll werden die Werte mit übertragen

**Comment by helgeerbe** [comment]
Wird leider nicht von den Ladegeratäten geliefert. Ist meines Wissens nur für den Smart Shunt spezifiziert.

**Comment by thorstenlutz** [comment]
Nach einer Recherche muss ich das leider bestätigen.
Die Temperatur wird nicht vom Victron Smartsolar übertragen, auch wenn ein Batteriesonsor mit dem Smartsolar per Bluetooth gekoppelt ist.
