### ISSUE TITLE
Home Assistant MQTT-Auto-Discovery / Ve.direct / Victron sensors become unavailable

### ISSUE THREAD

**Issue by madmartin** [helgeerbe/OpenDTU-OnBattery#279]
### What happened?

In Home Assistant, when Home Assistant MQTT-Auto-Discovery is active, almost all Sensors of the auto-discovered Victron device in Home Assistant become "unavailable" after a short time - except those Sensors with frequent changes like battery voltage or panel voltage.

### To Reproduce Bug

Set the following configuration:

MQTT Settings:
-  Home Assistant MQTT-Auto-Discovery -> active
-  Enable expiration -> active 

Ve.direct Settings:
- Enable Ve.direct -> active
- Send only updates -> active

### Expected Behavior

All sensors belonging to auto-discovered Victron chargers should show their values instead of "unavailable", as long as OpenDTU-OnBattery is running and Ve.Direct connection is enabled.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

n/a

### Anything else?

I am working on a PR for this.

**Comment by helgeerbe** [comment]
Merged in release 2023.07.09
