### ISSUE TITLE
Pin mapping missing after upgrading to 2023.06.23

### ISSUE THREAD

**Issue by dszam** [helgeerbe/OpenDTU-OnBattery#281]
### What happened?

I downloaded the opendtu-on-battery-generic.bin to upgrade from release 2023.06.14 to 2023.06.23.
After the upgrade I saw 

`[Pylontech] Twai driver get status - invalid state`

messages in the console. After investigating, I found that the pin mapping in "Hardware -> Standardprofil" was missing/incorrect for ve.direct and battery.
Attached is a screenshot of the wrong settings after the upgrade.
After downgrading to 2023.06.14 again, all pin mappings were correct again.

![Screenshot_2023-06-28_10-04-00](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/10998288/ec1d4b57-caa7-4eda-b1ff-4c55ded18c27)

To get it working again, I needed to create a custom pin_mapping.json and upload it.

### To Reproduce Bug

- upgrade from 2023-06-14 to 2023-06-23 by using the "generic" bin file.
- look at the console
- look at the hardware settings -> standard profile

Components are Smartsolar MPPT 100/20 and a pylontech compatible battery using can.

### Expected Behavior

the pin settings stay as they are, after upgrading the firmware

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2223afa

**Comment by Manos1966** [comment]
Thanks for posting this.
Upgraded this morning and changed HW.
I almost went crazy trying to understand what went wrong....

**Comment by madmartin** [comment]
I also upgraded two days ago to https://github.com/helgeerbe/OpenDTU-OnBattery/commit/2223afac627585a175c78f425cf43a8a17dd1b6f and did NOT have this problem.

BUT i compiled it myself, did not use a downloaded binary.

**Comment by Manos1966** [comment]
> I compiled it myself, did not use a downloaded binary.

Angeber!  :-p
Was it "opendtu-onbattery-generic.bin", update by OTA
Upgraded three systems (testing various setups in parallel) by OTA, all had the same result (Victron pins became 255).
This was the Firmware Page I got them from this morning:
![Capture](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/7b8d509f-1369-4a7d-9f5e-52209337b8fe)

**Comment by helgeerbe** [comment]
It seems, that this is the intended behavior. With version v23.6.21 in the original OpenDTU pre-compiled bins don't have any pin config. If there is not pin_mapping.json the defaults values are used, which are -1 for OpenDTU-onBattery extensions.

If you are using the pre-compiled bin, you have to prepare one  pin_mapping.json and import it once into openDTU. After that, all following updates should work as expected, without uploading a pin_mapping.json again.

All who are compiling their own bin, don't have to do this, because pins default values are defined in platformio.ini.

But anyhow. Pin type changed from unit8_t to int8_t. That is the reason why 255 is shown instead of -1. Will fix it.

**Comment by schlimmchen** [comment]
Is it possible that @helgeerbe previously uploaded a firmware built with the `d1_mini_esp32` environment? I don't see how else people got a working board without uploading a `pin_mapping.json` and without building their own firmware. The `d1_mini_esp32` is the only environment that defines OpenDTU-OnBattery-specific pins, and the issue reporter did mention that previously both VE.Direct and Pylontech CAN were working without a `pin_mapping.json`.

**Comment by fwscholz** [comment]
Hello.
Sorry for the question.
How does such a `pin_mapping.json` file look like, containing the additional OnBattery pins only? (VE.Direct pins would be enough for me.)
Thanks!

**Comment by schlimmchen** [comment]
@fwscholz Have a look at https://github.com/helgeerbe/OpenDTU-OnBattery/blob/master/docs/DeviceProfiles.md It should make it clear.

**Comment by helgeerbe** [comment]
Not a bug
