### ISSUE TITLE
Pass-trough Spelling[Request]

### ISSUE THREAD

**Issue by Manos1966** [helgeerbe/OpenDTU-OnBattery#294]
### Is your feature request related to a problem? Please describe.

I do not want to play the "Klugscheisser" here but since you write perfect software, it is a pity to see a spelling error at the Dynamic Power limiter Settings. (Pass-through is written with an "h")

Instead of:
Aktiviere Solar Pass-trough (Deutsch)
Enable Solar-Passtrough (English)
Enable Solar-Passtrough (Francais)

And also in German, 
- Angestrebter Netzbezung instead of "Netzbezug"

- DC Spannung - Lastkorrekturfaktor:
Hinweis: Wenn Leistung von der Batterie abgegeben wird, bricht normalerweise die Spannung etwas ein. Damit nicht vorzeitig der Wechelrichter ausgeschaltet wird sobald der "Stop"-Schwellenwert erreicht wird, wird der hier angegebene Korrekturfaktor mit einberechnet. Korrigierte Spannung = DC Spannung + **(Aktuelle Leistung (W) + Korrekturfaktor).**
should be **(Aktuelle Leistung (W) x Korrekturfaktor).**

![Pass-throuh spelling](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/9f43bdbc-0cf8-42b3-8815-2aa25ef63fe1)

### Describe the solution you'd like

Aktiviere Solar Pass-through (Deutsch)
Enable Solar-Passthrough (English)
Enable Solar-Passthrough (Francais)

German Angestrebter Netzbezung should be Angestrebter Netzbezug 
German Hinweis DC Spannung - Lastkorrekturfaktor should be (Aktuelle Leistung (W) x Korrekturfaktor).

**Comment by helgeerbe** [comment]
Should be fixed with ffa9be0835b4721ed18bb67acc743bcf545532ca
