### ISSUE TITLE
Power meter value not displayed

### ISSUE THREAD

**Issue by alexz707** [helgeerbe/OpenDTU-OnBattery#355]
### What happened?

The third phase json path is not prefilled with the value which was set before.

If someone wants e.g. to switch off the logging and presses save it won't work because phase 3 json path must not be empty.
![Bildschirmfoto 2023-08-04 um 21 18 08](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/562324/d92f728b-9d4b-4fa5-83ec-78c6704b6c0a)

### To Reproduce Bug

Set up https+ json with one request for all phases.
Add for each phase a different json path.
Save it, reload the page

json path of the third phase is empty the other two are filled out

### Expected Behavior

all 3 json paths are filled out

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

81864b3

**Comment by helgeerbe** [comment]
Thanks for reporting. I can confirm the error.

**Comment by helgeerbe** [comment]
Should be fixed with release 2023.08.08. Can you test it and close the issue, if you can confirm the fix.

**Comment by alexz707** [comment]
Thanks for the fast response!  i can confirm the fix :)
