### ISSUE TITLE
Schalter "Ausführliche Protokollierung" bei "Dynamic Power limiter Settings" ohne Funktion --> immer ON

### ISSUE THREAD

**Issue by peff74** [helgeerbe/OpenDTU-OnBattery#361]
### What happened?

Schalter "Ausführliche Protokollierung" bei "Dynamic Power limiter Settings" ohne Funktion --> immer ON

### To Reproduce Bug

schiebe den Switch auf Off, speichere, danach steht er wieder auf ON

### Expected Behavior

Nach dem umschalten auf OFF und speichern, steht der Schalter weiterhin auf ON und im Log werden die ausführlichen Infos zum Dynamic Power limiter ausgeben,

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

81864b3

**Comment by schlimmchen** [comment]
Oh man, du hast recht, wie peinlich... Ich schau es mir sofort an.

**Comment by helgeerbe** [comment]
Ich mach gleich mal eine Release 2023.08.07
