### ISSUE TITLE
Fehlermeldung für Hoymiles MQTT-Entitäten in neuer Version von Homeassistant

### ISSUE THREAD

**Issue by Napizaki** [helgeerbe/OpenDTU-OnBattery#377]
### What happened?

Erkannte Entitäten mit einem Namen, der mit dem Gerätenamen beginnt:

![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/126354867/dded7141-278b-4bcd-8e5e-0b51a9a94072)

### To Reproduce Bug

- Homeassistant Version >= 2023.08.00
- Home Assistant MQTT-Auto-Discovery aktivieren

### Expected Behavior

MQTT-Entitäten so umbenennen wie bei Victron oder Pylontech.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

5a72d74

**Comment by alexz707** [comment]
Dürfte damit zusammenhängen:

https://github.com/tbnobody/OpenDTU/issues/1194

**Comment by madmartin** [comment]
Ja, und wird auch dort gefixt. Die Meldung hier ist sozusagen nur zur Info.
