### ISSUE TITLE
HTTP power meter request fails when username or password contains @

### ISSUE THREAD

**Issue by markus-k** [helgeerbe/OpenDTU-OnBattery#450]
### What happened?

The HTTP power meter basic authentication fails when the username or passwords contain an @ (or other illegal characters). This results in an error (like host not found), because the URL is just added together instead of properly building an Authorization header: 

https://github.com/helgeerbe/OpenDTU-OnBattery/blob/4d0f9589431995f6c76b557973d9714cb5700fdb/src/HttpPowerMeter.cpp#L67-L76

A possible workaround is to build the Authorization header yourself and specify it in the UI, but thats not very user friendly.

### To Reproduce Bug

Use a username like foo@bar

### Expected Behavior

The requests succeeds.

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

4d0f9589431995f6c76b557973d9714cb5700fdb

**Comment by helgeerbe** [comment]
Sorry, was a little bit lazy and encoded user name and password in the url. With 160d3f23bd3e640aba527aea2de51eebf8148ecf authorization header is used instead.
