### ISSUE TITLE
IR Reader directly At ESP32(OpenDTUonBattery) SML , Easymeter

### ISSUE THREAD

**Issue by newt32** [helgeerbe/OpenDTU-OnBattery#498]
### What happened?

I installed OpenDTUonBattery at my ESP32. 
Connection with inverter HM1500 works fine and Open DTU shows the inverter infos and panel infos.
I connected an 4 PIN UART IR reader for mit smart meter (Easymeter Q3AA2054 , it has SML) **directly** to the OpenDTU (using 3,3V->3,3V , GND->GND, RX->GPIO35  , TX port on ir reader stay unused)
I set the powermeter "active" at openDTU an choose SML (Obis 16.7.0)
->now i can see the power of my Powermeter in my OpenDTUStarting-WebPage so the direct connection of IR Reader sems to work
I like this direct Connection because no Tasmota(ESP8266) needed, no wlan http(s) json request needed to transfer the power value from the ir-reader to the open DTU

**BUT "dynamic power limiter" doesn't work correcty now!**
->If i use IR->Tasmota with http(s) json request dynamic power limiter works fine 
->but with directly connected IR reader to open dtu und SML choosen for smart meter it doesn't work. **it sets the Hoymiles to 1% 9w and never changes again**

I don't think my power limiter settings are wrong (?) because with tasmota dynamic limiting works fine but with direct IR by SML it doesnt

So i think there must be a software problem.
**Open DTU is able to show the right power value of the powermeter on the screen but is it internally working with the right value?** setting the hoymiles to 1% 9w seems it's working with a wrong value? 
Will anybody test it. Will anybodes read the source and perhaps find a mistrake?

------------------
same in german:
ich habe den 4 poligen UART IR Reader **direkt** an die Open DTU angeschlossen (3,3v auf 3,3v , GND auf GND, RX auf GPIO35, TX bleibt frei)....feine Sache den Tasmota(esp8266) einzusparen, ein gerät weniger am strom vor allem aber brauch ich die stromzählerwerte nicht mehr per http json request abfragen lassen sondern der stromzähler liefert sie direkt alle 1 oder 2 sekunden per kabel. funktverbindung zum hoymiles recht bei mir offenbar auch aus
->stell ich bei power meter SML (OBIS...) ein kann ich auf der Open DTU Startseite meinen Stromverbrauch laut stromzähler korrekt sehen. Macht also den Eindruck als funktioniert es

ABER:
->dynamic Power limiter funktioniert nicht kofferekt. schalt ich das ein geht der hoymiles auf 1% 9w und verharrt dann da
->schließ ich den stromzähler dagegen an einem tasmota(esp8266) an und übertrage per https json die werte an die Open DTU zeigt er mir in der dtu genauso die spannung an und hier funktioniert dynamic power limiter korrekt

somit würde ich annehmen es liegt nicht an meinen dynamic power limiter settings?
er zeigt wie gesagt mit beiden auslesemethoden den wert in der weboberfläche der open dtu korrekt an.
es macht den Eindruck als rechnet er im falle der direkten übertragung per SML vielleicht mit einem falschem wert? (also nicht mit dem angezeigtem?)
Wär schön wenn jemand sich das ganze im Sourcecode mal anschaut vielleicht ist dort irgendwo ein Fehler.

### To Reproduce Bug

ir reader for powermeter directy connected to opendtu(esp32) ->powermeter sml(obis)->shows correct power value
BUT dynamic limiter doesnt work correctly (it sets hm1500 inverter to 1% 9w and never changes)

(with tasmota http json dynamic limiter works fine)

### Expected Behavior

dynamic limiter doesnt work correctly (it sets hm1500 inverter to 1% 9w and never changes)
->perhaps the limiter works with a wront power value?

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

4324ae3

**Comment by schlimmchen** [comment]
Please post the verbose logging output of the dynamic power limiter from the (web) console while the problem occurs.

**Comment by newt32** [comment]
RX Period End
18:22:40.891 > All missing
18:22:40.962 > Nothing received, resend whole request
18:22:41.021 > TX AlarmData Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E CB 00 00 00 00 00 00 00 00 BE F2 CA 
18:22:41.076 > Websocket: [/livedata][6] disconnect
18:22:41.326 > PowerMeterClass: TotalPower: 114.14
18:22:41.638 > RX Period End
18:22:41.714 > All missing
18:22:41.809 > Nothing received, resend whole request
18:22:41.860 > TX AlarmData Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E CB 00 00 00 00 00 00 00 00 BE F2 CA 
18:22:42.452 > RX Period End
18:22:42.520 > All missing
18:22:42.577 > Nothing received, resend whole request
18:22:42.648 > TX AlarmData Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E CB 00 00 00 00 00 00 00 00 BE F2 CA 
18:22:43.218 > RX Period End
18:22:43.287 > All missing
18:22:43.453 > Nothing received, resend count exeeded
18:22:43.503 > TX SystemConfigPara Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E CB 00 00 00 00 00 00 00 00 AA E6 DE 
18:22:43.569 > RX Period End
18:22:43.636 > All missing
18:22:43.692 > Nothing received, resend whole request
18:22:43.756 > TX SystemConfigPara Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E CB 00 00 00 00 00 00 00 00 AA E6 DE 
18:22:43.819 > RX Period End
18:22:43.961 > All missing
18:22:44.064 > Nothing received, resend whole request
18:22:44.128 > TX SystemConfigPara Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E CB 00 00 00 00 00 00 00 00 AA E6 DE 
18:22:44.199 > RX Period End
18:22:44.263 > All missing
18:22:44.374 > Nothing received, resend whole request
18:22:44.476 > TX SystemConfigPara Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E CB 00 00 00 00 00 00 00 00 AA E6 DE 
18:22:44.529 > RX Period End
18:22:44.680 > All missing
18:22:44.735 > Nothing received, resend whole request
18:22:44.890 > TX SystemConfigPara Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E CB 00 00 00 00 00 00 00 00 AA E6 DE 
18:22:44.964 > RX Period End
18:22:45.090 > All missing
18:22:45.198 > Nothing received, resend count exeeded
18:22:45.295 > Fetch inverter: 116183306302
18:22:45.364 > TX RealTimeRunData Channel: 23 --> 15 83 30 63 02 80 16 52 68 80 0B 00 65 29 6E D3 00 00 00 00 00 00 00 00 64 43 36 
18:22:45.420 > Interrupt received
18:22:45.489 > RX Channel: 75 --> 95 83 30 63 02 83 30 63 02 02 00 03 AF 84 00 B7 00 C4 01 09 00 02 00 02 00 04 C0 | -80 dBm
18:22:45.546 > Interrupt received
18:22:45.603 > RX Channel: 61 --> 95 83 30 63 02 83 30 63 02 03 00 04 00 03 78 16 00 03 57 C8 00 81 00 81 09 60 0A | -80 dBm
18:22:45.699 > Interrupt received
18:22:45.816 > RX Channel: 40 --> 95 83 30 63 02 83 30 63 02 84 13 88 00 00 00 E0 00 00 00 00 00 DC 00 01 71 48 8E | -80 dBm
18:22:45.868 > RX Period End
18:22:45.942 > Middle missing
18:22:46.004 > Request retransmit: 1
18:22:46.114 > TX RequestFrame Channel: 40 --> 15 83 30 63 02 80 16 52 68 81 EA 
18:22:46.214 > Interrupt received
18:22:46.269 > RX Channel: 3 --> 95 83 30 63 02 83 30 63 02 01 00 01 01 09 00 03 00 03 00 09 00 09 00 03 A4 78 42 | -80 dBm
18:22:46.419 > RX Period End
18:22:46.469 > Success
18:22:46.535 > [    718.156] DPL: power meter readings are outdated
18:22:49.533 > Fetch inverter: 116182805316
18:22:49.695 > Request SystemConfigPara
18:22:49.752 > TX RealTimeRunData Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E D8 00 00 00 00 00 00 00 00 54 30 EB 
18:22:50.165 > RX Period End
18:22:50.221 > All missing
18:22:50.290 > Nothing received, resend whole request
18:22:50.352 > TX RealTimeRunData Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E D8 00 00 00 00 00 00 00 00 54 30 EB 
18:22:50.714 > RX Period End
18:22:50.765 > All missing
18:22:50.819 > Nothing received, resend whole request
18:22:50.927 > TX RealTimeRunData Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E D8 00 00 00 00 00 00 00 00 54 30 EB 
18:22:51.277 > RX Period End
18:22:51.439 > All missing
18:22:51.539 > Nothing received, resend whole request
18:22:51.670 > TX RealTimeRunData Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E D8 00 00 00 00 00 00 00 00 54 30 EB 
18:22:51.849 > RX Period End
18:22:51.909 > All missing
18:22:52.052 > Nothing received, resend whole request
18:22:52.108 > TX RealTimeRunData Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E D8 00 00 00 00 00 00 00 00 54 30 EB 
18:22:52.326 > PowerMeterClass: TotalPower: 108.91
18:22:52.462 > RX Period End
18:22:52.560 > All missing
18:22:52.665 > Nothing received, resend count exeeded
18:22:52.738 > TX AlarmData Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E D8 00 00 00 00 00 00 00 00 8E 2B 30 
18:22:53.224 > RX Period End
18:22:53.296 > All missing
18:22:53.361 > Nothing received, resend whole request
18:22:53.417 > TX AlarmData Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E D8 00 00 00 00 00 00 00 00 8E 2B 30 
18:22:54.017 > RX Period End
18:22:54.106 > All missing
18:22:54.163 > Nothing received, resend whole request
18:22:54.214 > TX AlarmData Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E D8 00 00 00 00 00 00 00 00 8E 2B 30 
18:22:54.833 > RX Period End
18:22:54.903 > All missing
18:22:55.035 > Nothing received, resend whole request
18:22:55.124 > TX AlarmData Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E D8 00 00 00 00 00 00 00 00 8E 2B 30 
18:22:55.636 > RX Period End
18:22:55.737 > All missing
18:22:55.857 > Nothing received, resend whole request
18:22:55.951 > TX AlarmData Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E D8 00 00 00 00 00 00 00 00 8E 2B 30 
18:22:56.010 > [    728.163] DPL: power meter readings are outdated
18:22:56.410 > RX Period End
18:22:56.559 > All missing
18:22:56.663 > Nothing received, resend count exeeded
18:22:56.760 > TX SystemConfigPara Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E D8 00 00 00 00 00 00 00 00 9A 3F 24 
18:22:56.866 > RX Period End
18:22:56.930 > All missing
18:22:56.996 > Nothing received, resend whole request
18:22:57.062 > TX SystemConfigPara Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E D8 00 00 00 00 00 00 00 00 9A 3F 24 
18:22:57.170 > RX Period End
18:22:57.228 > All missing
18:22:57.289 > Nothing received, resend whole request
18:22:57.356 > TX SystemConfigPara Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E D8 00 00 00 00 00 00 00 00 9A 3F 24 
18:22:57.406 > RX Period End
18:22:57.465 > All missing
18:22:57.584 > Nothing received, resend whole request
18:22:57.650 > TX SystemConfigPara Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E D8 00 00 00 00 00 00 00 00 9A 3F 24 
18:22:57.707 > RX Period End
18:22:57.762 > All missing
18:22:57.842 > Nothing received, resend whole request
18:22:57.900 > TX SystemConfigPara Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E D8 00 00 00 00 00 00 00 00 9A 3F 24 
18:22:57.989 > RX Period End
18:22:58.046 > All missing
18:22:58.109 > Nothing received, resend count exeeded
18:22:58.163 > Fetch inverter: 116183306302
18:22:58.293 > TX RealTimeRunData Channel: 61 --> 15 83 30 63 02 80 16 52 68 80 0B 00 65 29 6E E0 00 00 00 00 00 00 00 00 95 03 B4 
18:22:58.361 > Interrupt received
18:22:58.417 > RX Channel: 3 --> 95 83 30 63 02 83 30 63 02 02 00 03 AF 84 00 B7 00 C4 01 08 00 02 00 02 00 04 C1 | -80 dBm
18:22:58.481 > Interrupt received
18:22:58.548 > RX Channel: 3 --> 95 83 30 63 02 83 30 63 02 03 00 04 00 03 78 16 00 03 57 C8 00 81 00 81 09 5A 30 | -80 dBm
18:22:58.619 > Interrupt received
18:22:58.684 > RX Channel: 75 --> 95 83 30 63 02 83 30 63 02 84 13 87 00 00 00 DF 00 00 00 00 00 DD 00 01 CD EE A5 | -80 dBm
18:22:58.744 > RX Period End
18:22:58.825 > Middle missing
18:22:58.880 > Request retransmit: 1
18:22:58.937 > TX RequestFrame Channel: 75 --> 15 83 30 63 02 80 16 52 68 81 EA 
18:22:59.008 > Interrupt received
18:22:59.067 > RX Channel: 23 --> 95 83 30 63 02 83 30 63 02 01 00 01 01 08 00 03 00 03 00 09 00 09 00 03 A4 78 43 | -80 dBm
18:22:59.230 > RX Period End
18:22:59.323 > Success
18:23:02.716 > Fetch inverter: 116182805316
18:23:02.800 > Request SystemConfigPara
18:23:02.902 > TX RealTimeRunData Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E E5 00 00 00 00 00 00 00 00 C5 3C 4B 
18:23:03.346 > RX Period End
18:23:03.524 > All missing
18:23:03.582 > Nothing received, resend whole request
18:23:03.730 > TX RealTimeRunData Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E E5 00 00 00 00 00 00 00 00 C5 3C 4B 
18:23:03.918 > RX Period End
18:23:03.994 > All missing
18:23:04.062 > Nothing received, resend whole request
18:23:04.113 > TX RealTimeRunData Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E E5 00 00 00 00 00 00 00 00 C5 3C 4B 
18:23:04.461 > RX Period End
18:23:04.518 > All missing
18:23:04.566 > Nothing received, resend whole request
18:23:04.618 > TX RealTimeRunData Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E E5 00 00 00 00 00 00 00 00 C5 3C 4B 
18:23:05.014 > RX Period End
18:23:05.075 > All missing
18:23:05.148 > Nothing received, resend whole request
18:23:05.203 > TX RealTimeRunData Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 0B 00 65 29 6E E5 00 00 00 00 00 00 00 00 C5 3C 4B 
18:23:05.529 > RX Period End
18:23:05.597 > All missing
18:23:05.769 > Nothing received, resend count exeeded
18:23:05.830 > TX AlarmData Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E E5 00 00 00 00 00 00 00 00 1F 27 90 
18:23:05.888 > [    738.172] DPL: power meter readings are outdated
18:23:06.401 > RX Period End
18:23:06.476 > All missing
18:23:06.537 > Nothing received, resend whole request
18:23:06.592 > TX AlarmData Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E E5 00 00 00 00 00 00 00 00 1F 27 90 
18:23:07.206 > RX Period End
18:23:07.267 > All missing
18:23:07.323 > Nothing received, resend whole request
18:23:07.422 > TX AlarmData Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E E5 00 00 00 00 00 00 00 00 1F 27 90 
18:23:08.018 > RX Period End
18:23:08.081 > All missing
18:23:08.146 > Nothing received, resend whole request
18:23:08.205 > TX AlarmData Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E E5 00 00 00 00 00 00 00 00 1F 27 90 
18:23:08.841 > RX Period End
18:23:08.953 > All missing
18:23:09.052 > Nothing received, resend whole request
18:23:09.108 > TX AlarmData Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 11 00 65 29 6E E5 00 00 00 00 00 00 00 00 1F 27 90 
18:23:09.334 > PowerMeterClass: TotalPower: 117.48
18:23:09.593 > RX Period End
18:23:09.656 > All missing
18:23:09.767 > Nothing received, resend count exeeded
18:23:09.822 > TX SystemConfigPara Channel: 3 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E E5 00 00 00 00 00 00 00 00 0B 33 84 
18:23:09.974 > RX Period End
18:23:10.032 > All missing
18:23:10.087 > Nothing received, resend whole request
18:23:10.190 > TX SystemConfigPara Channel: 23 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E E5 00 00 00 00 00 00 00 00 0B 33 84 
18:23:10.240 > RX Period End
18:23:10.312 > All missing
18:23:10.369 > Nothing received, resend whole request
18:23:10.440 > TX SystemConfigPara Channel: 40 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E E5 00 00 00 00 00 00 00 00 0B 33 84 
18:23:10.591 > RX Period End
18:23:10.642 > All missing
18:23:10.789 > Nothing received, resend whole request
18:23:10.891 > TX SystemConfigPara Channel: 61 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E E5 00 00 00 00 00 00 00 00 0B 33 84 
18:23:10.941 > RX Period End
18:23:11.105 > All missing
18:23:11.169 > Nothing received, resend whole request
18:23:11.255 > TX SystemConfigPara Channel: 75 --> 15 82 80 53 16 80 16 52 68 80 05 00 65 29 6E E5 00 00 00 00 00 00 00 00 0B 33 84 
18:23:11.320 > RX Period End
18:23:11.389 > All missing
18:23:11.447 > Nothing received, resend count exeeded
18:23:11.514 > Fetch inverter: 116183306302
18:23:11.575 > TX RealTimeRunData Channel: 3 --> 15 83 30 63 02 80 16 52 68 80 0B 00 65 29 6E EE 00 00 00 00 00 00 00 00 F5 4F 96 
18:23:11.632 > Interrupt received
18:23:11.715 > RX Channel: 61 --> 95 83 30 63 02 83 30 63 02 01 00 01 01 08 00 03 00 03 00 09 00 09 00 03 A4 78 43 | -80 dBm
18:23:11.771 > Interrupt received
18:23:11.842 > RX Channel: 40 --> 95 83 30 63 02 83 30 63 02 02 00 03 AF 84 00 B7 00 C4 01 08 00 02 00 02 00 04 C1 | -80 dBm
18:23:11.906 > Interrupt received
18:23:11.956 > RX Channel: 40 --> 95 83 30 63 02 83 30 63 02 03 00 04 00 03 78 16 00 03 57 C8 00 81 00 81 09 5B 31 | -80 dBm
18:23:12.042 > Interrupt received
18:23:12.119 > RX Channel: 40 --> 95 83 30 63 02 83 30 63 02 84 13 87 00 00 00 DF 00 00 00 00 00 DC 00 01 0D 7E F4 | -80 dBm
18:23:12.186 > RX Period End
18:23:12.235 > Success

inverter is sleepy because late ofternoon but i guess the info "power meter readings are outdated" could be the problem?
message is to be found in PowerLimiter.cpp
https://github.com/helgeerbe/OpenDTU-OnBattery/blob/b461aff622355379b6020011fe89afcb9600a884/src/PowerLimiter.cpp#L32

**Comment by schlimmchen** [comment]
> [ 850.425] DPL: power meter readings are outdated

It seems the piece of code that reads the power meter using that interface does not set the "last update" timestamp when a new reading was completed. This suspicion is confirmed after reading the source code. The respective variable is never updated if the SML interface is used.

Please test this, I think there is a good chance that it fixes your issue: https://github.com/schlimmchen/OpenDTU-OnBattery/releases/tag/2023.10.16-sml-powermeter-timestamp

**Comment by newt32** [comment]
Hi,
very big thanks!!! , but:
i tried to test your release but i can't get it runnig because in your release the NRF24 settings are off?
so the dtu did not communicate with my hm1500 inverter.

settings/device/Nrf24 
clk |   | 18
cs |   | 5
en |   | 4
irq |   | 16
miso |   | 19
mosi |   | 23

in your release i have a -1 value at all the six nrf24 settings.
it would be nice if you compile it again with the right nrf24 settings und send it to me.

bye
stephan
ps: do you speak german? (would be easierr my english is a little bit sleepy...)
German: 
Vielen Dank schonmal, dass du dich Sache mit dem SML angenommen hast.
Ich habe deine Version probiert aber dort spricht die DTU aktuell leider nicht mit meinem HM1500 Wechselrichter (online ist er). Schau ich unter Hardware Settings ist unter NRF24 überall eine -1 eingetragen (in stelle der weiter oben im englischen text genannten werden). Deine Version spricht also meinen Wechselrichter nicht an, weil die NRF24 einstellungen fehlen?

**Wär schön, wenn du die Version nochmal mit den richtigen NRF24 Einstellungen compilierst.**
mein Programmieren ist schon eine Weile her, so dass ich das complilieren leider nicht hinbekomme.

Vielen Dank,
Gruß
Stephan

**Comment by newt32** [comment]
I uploaded a pinmapping.json by myself to have correct nrf24 settings.
**With the correctet nrf24 settings your release seems to run fine with sml + powerlimiter function. Great Work!!!**

it would be fine if you compile it with these standart(?) settings.

-----------
german:
ich habe jetzt von Hand eine pin mapping.json datei in meine DTU hochgeladen um die richtigen nrf24 Einstellungen zu haben.
Es sieht so aus als funktioniert deine Anpassung bezüglich des SML Auslesens für die Nulleinspeisung!
->Es wäre toll, wenn du diese Anpassung nochmal mit den richtigen (standard?) NRF24 Einstellungen compilierst so, dass sie direkt verwendbar ist (also ohne diesen Umweg der manuellen Einstellungen)
->natürlich wäre es auch hilfreich, wenn diese Änderung generell in die Open DTU On Battery einfließt, eben damit die SML Funktion mit direkter Verkablung dann läuft für den der diesen Weg gehen möchte. 

War das jetzt ein allgemeiner "Fehler" den du dort ausgemerzt hast oder hängt es vom konkretrem Stromzählertyp und dessen SML Übermittlung ab ob das Problem was ich hatte auftritt oder nicht?

**Comment by schlimmchen** [comment]
Schön, dass du es getestet hast und es hinbekommen hast! Danke.

> Es wäre toll, wenn du diese Anpassung nochmal mit den richtigen (standard?) NRF24 Einstellungen compilierst

Da muss ich dir eine Absage machen. Ich weiß nicht, was ich dafür bauen muss. Außerdem ist es der ritchtige und gewollte Weg, dass jeder eine `pin_mapping.json` für sein Gerät erstellen und hochladen muss. Ggf. gibt es für beliebte Boards Beispiele oder vollständige JSON-Dateien, die man nur noch hochladen muss. Dass zuvor Standard-Pins festgelegt waren, ist nach allem was ich verstanden habe aus dem Ruder gelaufen und wird zurückgebaut. Bitte pflege deine `pin_mapping.json`.

> natürlich wäre es auch hilfreich, wenn diese Änderung generell in die Open DTU On Battery einfließt

Ja, natürlich. Das sollte kein exklusiver Fix für dich werden :wink: Aber ich musste das jemanden testen lassen, bevor ich einen pull request erstelle.

> War das jetzt ein allgemeiner "Fehler"

Der Fehler tritt immer auf, wenn jemand per SML einen PowerMeter lesen will. MQTT, HTTP+JSON und SDM waren davon nicht betroffen.

**Comment by newt32** [comment]
Hallo,
alles klar, vielen Dank schonmal - Respekt und vor allem Danke für den ganzen Aufwand.

Etwas überrascht bin ich ja, dass die SML Funktion schon auswählbar war aber diese direkte Verkablung offenbar noch kaum jemand(keiner?) umgsetzt hat (sonst wäre der Fehler sicherlich schon wem aufgefallen, wobei das ja nicht heißt dass jeder ihn hier meldet).

Was das Pin Mapping angeht:
Ich wußte natürlich erstmal gar nicht wie ich das verändere. Habs dann mit etwas Suchen gefunden. Das Hochladen der json Datei ist natürlich auch etwas versteckt in der Listbox "Wiederherstellen: Wiederherstellen der Konfigurationsdatei"
->hier wäre unter "Hardware Einstellungen" eine kleiner Infotext hilfreich wie man diese verändern kann und in welchem Menü man die entsprechende .json datei hochladen kann
->unter Konfiguration: Wiederherstellen der Konfigurationsdatei(**en**) ....(das **en** fehlt) muss man dann erstmal drauf kommen, dass hier in der Listbox neben "Main konfig" noch ein "Pin Mappig" ausgewählt werden kann. **Lieber keine Listbox sondern eine zweite Datei Uploadzeile wäre hier in meinne Augen einfacher zu finden.**
->unter Sicherung der Konfigurationsdatei kann ich nur die 'Main konfig' json sichern aber nicht die 'Pin Mapping' json. Klar letzteres kann ich ja von Hand in der DTU gar nicht verändern, sondern nur per Datei Upload. Dennoch wäre es ja sinnvoll, wenn ich von dem Firmware Build welches ich gerade installiert habe auch das Pin Mappig sichern kann um beide .json dateien miteinander vergleichen zu können.
--------- 
Davon unabhäng zwei kleinere Bugs (oder evtl auch Feature?) :
a) Schalte ich die PowerLimiter Funktion ab würde ich - aktuell keine Batterie am laufen - erwarten, dass der Wechserichter wieder in seine "vorherige Einstellung" geht (bei mir wären das 100% also keinerlei Drosslung). Das macht er aber nicht.
Ganz offensichtlich regelt er sich runter auf 1% 9w (niedrigstes Limit) und geht dann in den Shutdown
->nun könnte man denken dass er nicht einfach wieder auf 100% geht ist ein Feature, eben für den Fall dass ein Akku dahinterhängt der bei 100% ja mit 100% Wechselrichterleistung leergesaugt wird
->schlauer wärs eigentlich der geht nach abschalten der Limiter funktion in das Limit was vor einschalten des Limiters eingestellt war (in meinem Fall halt 100%). Nun weiß ich nicht ob die DTU bei längerem Betrieb diesen Wert überhaupt irgendwo speichern kann?
Zweite Sache die in diesem Zusammenhang auffällt:
->Starte ich den Inverter (nach runterfahren durch ausschalten des powerlimiters) anschließend neu (HM1500) läuft er auch wieder auf 100%. Allerdings **zeigt** er mir bei aktuelles Limit den letzten Wert nämlich 1% 9W an. **Die Anzeige im Statursfeld des Inverters zeigt also dann einen falschen Wert.**

b)Nehme ich meinen IR Lesekopf vom Stromzähler (so dass die DTU quasi keine SML Daten mehr bekommt) verharrt der Leistungswert der in der OpenDTU **angezeigt** wird beim letztgelesenem Wert.
->ich würde erwarten, dass dann 0 angezeigt wird oder als Anzeige "ERROR no SML Data from Powermeter"
(ich denke mal bei http json abfrage passiert das gleiche also alter wert angezeigt aber kein error "no http .json data from powermeter")
->der Limiter geht auf 1% 9w und der Inverter dann in den Standby, was vermutlich auch sinnvoll ist(im einen Akku zu schützen oder eben einfach NULLeinzuspeisen). Er scheint also immerhin nicht mit dem alten - in der DTU angezeigten - Wert weiterzurechnen (bei 0 wäre das nicht schlimm. bei 2000w weil grad der herd mit 2200w läuft und der wechselrichter 200 zusteuer schon) **also ist der Fehler hier wohl nur im "angezeigtem Wert".**
