### ISSUE TITLE
Button "Speichern" (Submit) in setting screens very small + label missing

### ISSUE THREAD

**Issue by CaCu15** [helgeerbe/OpenDTU-OnBattery#568]
### What happened?

Just upgraded to the release [2023.12.27.post1](https://github.com/helgeerbe/OpenDTU-OnBattery/releases/tag/2023.12.27.post1).

Everything works fine, but in the settings screen the button to submit the changes is VERY small, only a small blue area without any label.  See attached screenshot. The button still works, you can save the settings, thus it is only a minor visual issue.

Happens in the follwing screens:
- VE Direct settings
- Power meter settings
- Dynamic Power Limiter settings
- Battery settings
- AC Charger settings

![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/34535696/6c44aec4-2325-4e13-9919-44de647d4f0f)

### To Reproduce Bug

Open any settings dialog listed above

### Expected Behavior

Button should look like in the other setting screens and should be labeled "Speichern" (in the German version)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2023.12.27.post1

**Comment by schlimmchen** [comment]
Tatsächlich. Dass das nur OpenDTU-OnBattery-spezifische Seiten sind, ist sicherlich kein Zufall... Ich denke das Problem ist schnell gefunden.
