### ISSUE TITLE
Ok hab jetzt mal die Startspannung auf 24Volt gesetzt. passiert  aber das gleich. was ich nicht verstehe 

### ISSUE THREAD

**Issue by Agerter** [helgeerbe/OpenDTU-OnBattery#604]
Ok super für die schnelle Antwort das teste ich gleich mal

_Originally posted by @Agerter in https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/592#discussioncomment-8113485_

**Comment by schlimmchen** [comment]
Ich nehme stark an, dass dieses Issue aus Versehen erstellt wurde, daher schließe ich es.
