### ISSUE TITLE
Dynamic Power Limiter stoppt den Wechselrichter nicht bis die Akku SoC - Start Werte erreicht werden  

### ISSUE THREAD

**Issue by Manos1966** [helgeerbe/OpenDTU-OnBattery#610]
### What happened?

Ich verstehe es nicht...

Meine Pylontech ist bei 30% SOC und ich will sie heute bis zu 95% laden.
Daher:
- Akku SOC - Start: 90%
- DC Spannung - Start: 52V (Vorsichtshalber)
- Strategie: "Leeren, wenn voll" oder "Leeren zur Nacht" (kein Unterschied)
- Aktuelste Firmware (2024.001.07)
- Neustart der OpenDTUonBattery

Mit diesen Eistellungen, sollte der Wechselrichter aufhoeren zu produzieren und warten, bis die Akku SOC die 90% erreicht, bevor er wieder anfaengt.

**Dies ist leider NICHT der Fall. Der Wechselrichter fängt sofort zu produzieren** 
Neustart der OpenDTU, Neustart des Wechselrichters, Firmware Update : Nichts hat geholfen.

Mache ich etwas falsch, oder ist es ein Bug?

Bilder anbei:
BatterieStand
![BatterieStand](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/a2056440-56d6-4433-ba46-1c5b6cbc554b)
PowerLimiter Settings
![PowerLimiter](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/3085ade7-3911-478f-a86d-4829a47b4b78)
Wechselrichter
![Wechselrichter](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/277e0612-0980-4743-aca8-edf2a15e2f02)
Victron
![Victron](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/4209d8d4-c1f1-42b2-b7c4-f96069453821)

### To Reproduce Bug

Just normal operation using Dynamic Power Limiter and setting a high Battery Start SOC % limit

### Expected Behavior

"Akku SoC - Start %" muss erst erreicht werden bevor der Wechselrichter starten soll Strom zu produzieren.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.01.7.post1

### Relevant log/trace output

```Shell
RX Period End
12:27:18.726 > Last missing
12:27:18.831 > Request retransmit: 3
12:27:18.962 > TX RequestFrame Channel: 61 --> 15 74 40 20 87 80 16 00 72 83 E1 
12:27:19.032 > RX Period End
12:27:19.154 > Last missing
12:27:19.212 > Request retransmit: 3
12:27:19.295 > TX RequestFrame Channel: 75 --> 15 74 40 20 87 80 16 00 72 83 E1 
12:27:19.384 > [    562.716] DPL: waiting for sufficiently recent inverter data
12:27:19.443 > [Pylontech] Alarms: 0 0 0 0 0 0 012:27:19.572 > [Pylontech] Warnings: 0 0 0 0 0 0 012:27:19.645 > [Pylontech] chargeVoltage: 53.200001 chargeCurrentLimitation: 80.000000 dischargeCurrentLimitation: 80.00000012:27:19.718 > Interrupt received
12:27:19.863 > [Pylontech] soc: 32 soh: 10012:27:19.924 > RX Channel: 40 --> 95 74 40 20 87 74 40 20 87 81 00 01 70 C0 A5 | -80 dBm
12:27:19.982 > [Pylontech] voltage: 50.419998 current: 16.900000 temperature: 10.90000112:27:20.204 > [Pylontech] chargeStatusBits: 1 1 012:27:20.316 > RX Period End
12:27:20.410 > Success
12:27:53.325 > [DPL::loop] ******************* ENTER **********************
12:27:53.399 > [DPL::loop] battery interface enabled, SoC: 32 %, StartTH: 90 %, StopTH: 12 %, SoC age: 1 s
12:27:53.559 > [DPL::loop] dcVoltage: 50.60 V, loadCorrectedVoltage: 50.77 V, StartTH: 52.00 V, StopTH: 47.00 V
12:27:53.637 > [DPL::loop] StartTH reached: no, StopTH reached: no, inverter is producing
12:27:53.695 > [DPL::loop] SolarPT enabled, Drain Strategy: 1, canUseDirectSolarPower: yes
12:27:53.767 > [DPL::loop] battery discharging prevented, PowerMeter: -44 W, target consumption: -50 W
```

**Comment by helgeerbe** [comment]
Du hast Solar-Passthrough an. Wenn die Sonne scheint, wird der Strom direkt in dein Hausnetzt eingespeisst. Und zwar in der Höhe, wie du ihn verbrauchen kannst. Was passiert, wenn du das deaktivierst?

**Comment by Manos1966** [comment]
Danke @helgeerbe 
Verdammt! Wieder wie ein Anfaenger rein gefallen 😡 🤦‍♂️ 

Solar-Passthrough aus, alles funktioniert wie erwartet:

![Solved](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/0b298e0c-b986-44f3-b4bf-c4802feaf59f)

**Comment by spcqike** [comment]
wie @helgeerbe sagt, du nutzt solar-passtrough. und das ist (eigentlich) gut, da du Umwandlungsverluste vermeidest und damit die Effizienz erhöhst.

deine Antwort liegt auch im Log

12:27:51.294 > [DPL::loop] **StartTH reached: no**, StopTH reached: no, inverter is producing
12:27:51.359 > [DPL::loop] **SolarPT enabled**, Drain Strategy: 1, **canUseDirectSolarPower: yes**
12:27:51.428 > [DPL::loop] battery discharging prevented, PowerMeter: -48 W, target consumption: -50 W
12:27:51.499 > [DPL::loop] **Consuming Solar Power Only -> adjustedVictronChargePower: 922 W**, newPowerLimit: 134 W

in deinen Screens siehst du es quasi auch. der Victron erzeugt 467W, davon speist du direkt 168W ein. 

warum in deinem Bild die Batterie allerdings mit 455W entladen werden soll, verstehe ich nicht. (oder heißt das laden und entladen wären -xxx W?)

**Comment by Manos1966** [comment]
Danke Helge!

und Danke Martin fuer die Beschreibung des Logs!
