### ISSUE TITLE
VE.Direct wo aktivieren

### ISSUE THREAD

**Issue by eeprom23** [helgeerbe/OpenDTU-OnBattery#617]
### What happened?

Wo kann ich das auslesen eine MPPT von Victron activieren ? rx und tx habe ich am esp verbunden über pin 21 und 22. jedoch finde ich keine option das auslesen zu starten !

### To Reproduce Bug

![Screenshot 2024-01-21 164145](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/37772803/1e8e56cc-0610-4018-b347-44dd28fce31c)

### Expected Behavior

habe den esp32 schon mehrfach neu geflashed und auch eine neuere version genutzt. edoch finde ich die option nicht.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

7492acd

### Relevant log/trace output

```Shell
-
```

### Anything else?

-

**Comment by schlimmchen** [comment]
In der Web-App unter "Einstellungen" "VE.Direct" wählen und einschalten?!

Aber dein Pin-Mapping sieht noch falsch aus. Welches Hardware-Profil/Pin-Mapping hast du denn ausgewählt im Drop-Down-Menü? Den Teil sieht man nicht im Screenshot.

**Comment by eeprom23** [comment]
diese einstellung gibt es leider nicht !
![Screenshot 2024-01-21 171116](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/37772803/ca12209a-4de0-4d73-9256-283e9782e07c)
![Screenshot 2024-01-21 171138](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/37772803/451c4266-e1e8-4c0b-b1f5-9ad969c3c50d)

**Comment by Manos1966** [comment]
Eine Profile Datei fehlt...
https://github.com/helgeerbe/OpenDTU-OnBattery/wiki/Device-Profiles

**Comment by Solarteur** [comment]
Ist da überhaupt OpenDTU-**OnBattery** installiert? Bei mir sieht das Menu unter "Hardware" so aus:

![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/117977338/422190ce-080d-4490-a52b-8585fdd2e51a)

**Comment by schlimmchen** [comment]
Er kommt wahrscheinlich von OpenDTU (nicht OpenDTU-OnBattery) und muss die WebApp aktualisieren.

@eeprom23 Bitte drücke Strg+F5 in deinem Browser, falls meine Vermutung stimmt, dass du zuvor das Upstream-Projekt "OpenDTU" installiert hattest auf diesem ESP32.

**Comment by Manos1966** [comment]
@Solarteur 🤣🤣🤣🤣🤣🤣🤣🤣 👍 
Oh Man, ich muss zu Fielmann....
![Capture](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/1b55f122-eb28-4266-a5c8-046289128b8a)

**Comment by eeprom23** [comment]
Vielen Dank, ich bin irgenwie auf die normale Open DTu gekommen ! Danke für eure schnell Hilfe !!

**Comment by schlimmchen** [comment]
@eeprom23 Bitte schließe das Issue als erledigt.
