### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Koller417** [helgeerbe/OpenDTU-OnBattery#624]
### What happened?

Fehlermeldung nach Update

### To Reproduce Bug

[HTTP ERROR] Bad Request

### Expected Behavior

Neustart

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.01.26

**Comment by helgeerbe** [comment]
Kommt da noch was? [HTTP ERROR] Bad Request kann alles sein. Kein Strom. Netzwerkprobleme.... 
Wie hast du das Update durchgeführt? OTA oder über Kabel. Was passiert, wenn du den ESP  neu startest (stromlos machen, oder Knopf drücken)? 

So kann ich dir nicht helfen. Ausser sagen, dass es bei mir auf 3 ESPs läuft.

**Comment by Koller417** [comment]
Nein. Update wird über OTA ausgeführt.Nach Neustart ist die alte Version noch drauf.

**Comment by Solarteur** [comment]
Gerade bei mir über OTA auf 2024.01.26 aktualisert - keinerlei Probleme.

**Comment by schlimmchen** [comment]
Klingt nach "Binary zu groß", also veraltetes Partitionsschema oder die Firmwarr ist für einen bestimmten ESP32 tatsächlich übergelaufen. Aber das würde wohl beim Build auffallen. Welchen ESP32 hast du genau? Welche Firmware-Datei nimmst du?

Bitte Konfig sichern, die passende factory-Bibary über die serielle Schnittstelle programmieren und Konfig wiederherstellen.

**Comment by Koller417** [comment]
Auch über Kabel nicht instalierbar. Version 2024.01.16 läst sich über Kabel und OTA instalieren.

**Comment by Koller417** [comment]
ESP32 WROOM 32.
generic_32.bin

**Comment by Koller417** [comment]
Version 24.1.21 wird über OTA installiert.

**Comment by Tiese** [comment]
Bei mir kam die gleiche Fehlermeldung!
Ich habe auf **_wiederholen_** geklickt, dann ging es reibungslos &#128515;

**Comment by schlimmchen** [comment]
@Koller417 Dann hattest du also Erfolg und dieses Issue kann geschlossen werden?
