### ISSUE TITLE
Add new SmartSolar MPPT 150/45 Rev3

### ISSUE THREAD

**Issue by hhoebel** [helgeerbe/OpenDTU-OnBattery#641]
### Is your feature request related to a problem? Please describe.

I'm owner of a brand new Victron SmartSolar MPPT 150/45 which isn't recognized by OpenDTU-OnBattery (reported as "???")

### Describe the solution you'd like

The console reports the PID as 0xA073, so i suggest to add the line
{ 0xA073, "SmartSolar MPPT 150|45 rev3" },
to VeDirectFrameHandler.cpp

**Comment by schlimmchen** [comment]
Why "rev 3"? There already is a "SmartSolar MPPT 150|45" but yours is revision three and that has a new PID?

Can you find a canonical source for the PIDs? This would be cause to update the whole list, not just add one particular product.

Implementing this is straight-forward, you already found the right spot.

**Comment by hhoebel** [comment]
Sorry, nein, ich hatte keine Quelle dafür und nur vermutet, das die neuere PID dann Rev3 bedeutet. Ich habe nach deinem Post aber nochmal gesucht und tatsächlich was in der Doku des VE.Direct-Hex-Protokolls bei Victron gefunden - die scheint ziemlich aktuell zu sein:
https://www.victronenergy.com/upload/documents/BlueSolar-HEX-protocol.pdf (ab Seite 4). 
Danke übrigens für OpenDTU OnBattery :-)
