### ISSUE TITLE
Bitte dieses Issue LÖSCHEN

### ISSUE THREAD

**Issue by hoschiking** [helgeerbe/OpenDTU-OnBattery#652]

**Comment by hoschiking** [comment]
@skippermeister

Zufällig habe ich in einem anderen Thread den Screenshots entdeckt, dass du zur PV-Überschußladung einen Meanwell NPB verwendest. Wie geht das? Soweit ich es sehe, wird bisher nur der Huawei unterstützt, da ich aber mit 24V arbeite, kann ich den nicht verwenden. Ist damit auch eine PV-Überschußeinspeisung mit Ladestromregelung in Abhängigkeit des Überschußes realisierbar? Ich suche immer noch nach einer Lösung dafür.
Falls der Bereich "Issues" nicht der richtige ist, davon gehe ich aus, kann man den Thread verschieben?
Danke dir

**Comment by schlimmchen** [comment]
@hoschiking Kannst du dein Gesuch in eine neue Diskussion (kein Issue) verschieben, bitte?

**Comment by hoschiking** [comment]
Ja gerne, wenn ich wüßte wie. Ich könnte es auch löschen, finde den Button aber auch nicht.
Sorry dafür. Kann es nicht ein Admin machen?
Oder du erklärst einem Github Neuling freundlicher Weise wie das geht.
Danke dir

**Comment by hoschiking** [comment]
Fälschlicher Weise einen Beitrag unter Issues erstellt.
Sollte gelöscht werden.
