### ISSUE TITLE
DTU Abfrageintervall BUG

### ISSUE THREAD

**Issue by Cartman586** [helgeerbe/OpenDTU-OnBattery#674]
### What happened?

Beim einstellen oder ändern des Abfrageintervalls kommt die Fehlermeldung 
"Die Frequenz muss zwischen 860250000 und 923500000 kHz liegen und ein vielfaches von 250kHz betragen!"

### To Reproduce Bug

Einfach den Abfrageintervall ändern und speichern

### Expected Behavior

Speichern des Abfrageintervalls
![16-02-2024_06-31-46](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/124084915/b6861f18-0235-41a8-932b-2481cf536565)

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.02.09

**Comment by schlimmchen** [comment]
Das ist ein Bug aus dem Upstream-Projekt, bitte dort danach suchen, da gab es bereits entsprechende Issues. Da heißt es "Strg + F5" drücken um die WebApp neu zu laden. Allerdings scheint das nicht alles zu sein. Vermutlich ist ein ungültiges Frequenzband per default eingestellt gewesen und neuerdings ist das ungültig wegen der Überprüfung auf die Region.

**Comment by Cartman586** [comment]
Danke. Komme hier aber nicht weiter

**Comment by schlimmchen** [comment]
Als Workaround könntest du dir deine config.json als Backup herunterladen und editieren. Setze "cmt_frequency" auf "865000000" und "cmt_country_mode" auf "0". Speichere die Datei und lade sie wieder hoch. Versuche dann erneut das Polling-Interval umzustellen. Ich vermute, dass es dann geht. Falls ja, lass es uns bitte wissen.

**Comment by Cartman586** [comment]
> Als Workaround könntest du dir deine config.json als Backup herunterladen und editieren. Setze "cmt_frequency" auf "865000000" und "cmt_country_mode" auf "0". Speichere die Datei und lade sie wieder hoch. Versuche dann erneut das Polling-Interval umzustellen. Ich vermute, dass es dann geht. Falls ja, lass es uns bitte wissen.

Danke, komme hier leider nicht weiter

**Comment by Cartman586** [comment]
> Warum nicht?
> 
> tobi0171 hat [bestätigt](https://github.com/helgeerbe/OpenDTU-OnBattery/issues/639#issuecomment-1954107298), dass das Problem so zu umgehen ist. Ansonsten ist es wie gesagt ein Problem im Upstream-Projekt, melde ich dort bitte. Für uns ist hier nichts zu tun.

Habs soeben nochmal probiert, jetzt hat es mit dem Workaround geklappt. Danke

**Comment by uli-bs** [comment]
Auch von mir, die manuelle Datenänderung hat das Problem beseitigt, der Wert vorher war irgendwas mit "...204"
