### ISSUE TITLE
3 phase inverter showing summary as "phase 1" in LiveView

### ISSUE THREAD

**Issue by dpiller** [helgeerbe/OpenDTU-OnBattery#680]
### What happened?

While using a 3 phase microinverter (Hoymiles HMT-1800-6T in this case, but applicable to 2250-6T too) the summary window has a title "Phase 1" which is incorrect in that sense. 

![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/24863769/343bf66e-222e-462c-bfef-0bed6fd87e05)

### To Reproduce Bug

Live view showing a Hoymiles HMT-1800-6T or 2250-6T - 3 phase inverters 

### Expected Behavior

Assuming the delivered values are correct, please correct the title from "Phase 1" to "Phase 1 - 2 - 3".

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v4.4.6-dirty / 2024.01.26 / config 0.1.27 / master

**Comment by spcqike** [comment]
isn't that more of an issue for the upstream? 

https://github.com/tbnobody/OpenDTU/discussions/872

**Comment by schlimmchen** [comment]
Please report this [upstream](https://github.com/tbnobody/OpenDTU/issues).
