### ISSUE TITLE
Web UI - Grid Power not updated 

### ISSUE THREAD

**Issue by der-peterh** [helgeerbe/OpenDTU-OnBattery#682]
### What happened?

Shelly EM3 reading (summary) gets only updated on live data view reload but not during auto update.
MQTT (solar/powermeter/powertotal) updates fine.

### To Reproduce Bug

Shelly EM3 configured correctly - publishes expected results via  MQTT

### Expected Behavior

Live Data field 'Grid Power' gets updated in same frequency as other live data

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

2024.02.19.post1

### Anything else?

As my Shelly power clamps are installed in opposite direction, I needed to invert return value of PowerMeterClass::getPowerTotal
because I rather touch code than live power lines ;)

**Comment by OlSteph** [comment]
Same here with Shelly Pro 3em without MQTT (with RPC)
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/116741698/3d8aad22-9547-4135-a7ba-4d50f1358f28)
