### ISSUE TITLE
Add RS485 Pylontech support

### ISSUE THREAD

**Issue by Manos1966** [helgeerbe/OpenDTU-OnBattery#710]
### Is your feature request related to a problem? Please describe.

Currently threre is CANbus Support for Pylontech & other Batteries
The information CAN provides is good but limited compared to the information available from the RS485 port:
**CANbus Information currently:**
![CANbus Feedback](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/5175e201-06c6-407e-aa14-4e1eb86441a6)

**RS485 Information:**
![Master](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/be59ac06-ab39-4a32-8c84-ea8427b2dbd7)
![Slave-1](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/129660360/5b6cf0ce-393f-418d-a688-4a2f9465c067)

### Describe the solution you'd like

Add RS485 support to the OpenDTUonBattery in order to make the additional information available.

Additional Information: Both CANbus and RS485 are working at the same time = **There is no requirement to change the existing programming which uses the SOC% data from the CANbus**.
 
A solution exists already, monitoring multiple Pylontech Batteries:
#622 adding RS485 Pylontech support 

https://github.com/skippermeister/OpenDTU-OnBattery

### Describe alternatives you've considered

Use a separate ESP32 with the Fork von skippermeister
https://github.com/skippermeister/OpenDTU-OnBattery
Both OpenDTUs can be online, collecting information from the Pylontech Battery/ies, using the CANbus and RS485 connection at the same time.

**Comment by tobi0171** [comment]
Das wäre super ... ich würde mich freuen

**Comment by Solarteur** [comment]
Es gibt dazu einen Fork von skippermeister https://github.com/skippermeister/OpenDTU-OnBattery, der aber leider kein Huawei R4850G2 AC-Ladegerät unterstützt und deshalb für mich keine Option ist.

Andererseits sehe ich auch, dass der verfügbare Speicherplatz immer weiter schrumpft...

**Comment by Napizaki** [comment]
Ich fände es ebenfalls super. Vor Allem die Spannungen der einzelnen Zellen (min/max) fände ich interessant. Derzeit prüfe ich sowas immer manuell mit der Battery-View Software. Dieses wäre damit überflüssig.

**Comment by Manos1966** [comment]
> Andererseits sehe ich auch, dass der verfügbare Speicherplatz immer weiter schrumpft...

So gesehen, ich muss gestehen, ich habe kein Problem einen extra ESP32 fuer die Beobachtung der Pylontech Zellen zu haben (separat von der Haupt-OpenDTUonBattery Einheit.

Ich gehe davon aus, die Meisten von uns nutzen Homematic Systeme und sammeln Daten ueber MQTT. Dann waere es mir lieber, dass auf den Speicher der ersten OpenDTUonBattery die wichtige Real-Time Aufgaben laufen (z.B. zwei Victron MPPT, zwei Wechselrichter usw...) und auf andere "OpenDTUs" die restliche, non-critical Informationen.

**Comment by Manos1966** [comment]
I close this as I see it is more beneficiary to run an existing solution on a separate ESP32 than trying to add this feature to OpenDTUonBattery.
