### ISSUE TITLE
[Request] AC charger: Implement DC/Battery stop SoC

### ISSUE THREAD

**Issue by gitisgreat2023** [helgeerbe/OpenDTU-OnBattery#754]
### Is your feature request related to a problem? Please describe.

Currently stopping of the charging is defined by voltage. As both the start and stop threshold conditions are defined in SoC %s, adding a target to stop charging would make sense.

### Describe the solution you'd like

Adding Battery SoC - Stop charging.

To avoid confusion: best rename 
a) Battery SoC Stop threshold  to Battery SoC - Stop discharging 
b) Battery SoC - Start charging to Battery SoC - Allow discharging

**Comment by Manos1966** [comment]
Quick question for my understanding:
"Adding Battery SoC - Stop charging."

What are you using for charging?
Because as I understand, the VICTRON MPPTs are not receiving data from OpenDTU (in order to stop charging)

**Comment by schlimmchen** [comment]
There is no "stop charging". There is only "start discharging", or in other words "start using the battery for energy production".

I don't understand what you are asking for.

What should happen if the newly proposed "Battery SoC - Stop charging" threshold is reached?

**Comment by schlimmchen** [comment]
Is this about the Huawei charger?

**Comment by gitisgreat2023** [comment]
Yes, after reaching the "Battery SoC - Stop charging" threshold it should stop charging...

Currently there are two SoC values: stop discharge, start again discharging. For example 15% (stop) and after reaching 20% allow discharging again.

The third value would be the upper level to stop charging, like 90% or 95%. 

Yes my setup is a HM, Huawei, Pylontech setup.

**Comment by schlimmchen** [comment]
I think this is completed with #848, which will be included in the next release.

![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3578416/46b6e5f7-d4df-4ce0-9eb9-ebc6f764755f)

Please re-open this issue if I got it wrong.
