### ISSUE TITLE
[Request] Disable Full Solar-Passthrough

### ISSUE THREAD

**Issue by ottelo9** [helgeerbe/OpenDTU-OnBattery#773]
### Describe the solution you'd like

Es wäre gut, wenn man Full Solar-Passthrough komplett abschalten könnte. Ich möchte wirklich versuchen nichts einzuspeisen. Gestern hatte ich den Fall, Akku war voll (Leeren zur Nacht) und ich hab voll eingespeist. Leider kann ich bei "Akku SoC - Start solar passthrough" nicht mehr als 100 eingeben, das würde mein Problem schon lösen.

**Comment by schlimmchen** [comment]
Full Solar-Passthrough SoC-Schwellwert **und** Full Solar-Passthrough Spannungs-Schwellwert jeweils auf 0 einstellen. Neustarten (um auszuschließen, dass full solar passthrough gerade aktiv ist). Fertig. Kein Full Solar-Passthrough mehr.

Ich nehme an, dann ist kein zusätzlicher Schalter nötig?

**Comment by ottelo9** [comment]
Hey super danke. 

Mit _Full Solar-Passthrough SoC-Schwellwert_ ist _Battery SoC - Start threshold for full solar passthrough_ bzw. _Akku SoC - Start solar passthrough_ gemeint. Habe diesen Wert auf 0 gesetzt.

Mit _Full Solar-Passthrough Spannungs-Schwellwert_ ist _DC Voltage - Start threshold for full solar passthrough_ bzw. _DC Spannung - Start Solar-Passthrough_ gemeint. Diesen habe ich allerdings auch auf 0 gestellt. Im Source Code wird ja die Funktion testThreshold() gerufen und diese beiden Parameter übergeben. Wenn beide auf 0 gesetzt sind wird immer false ausgegeben und somit Full Solar-Passthrough immer deaktiviert. Die 0 sollten keine Probleme machen. 66 kannman natürlich auch setzen, wollte aber was offensichtliches wie eine 0 reinsetzen.

**Comment by schlimmchen** [comment]
> Der Victron MPPT 100/20 hält dann die Spannung am Ausgang aber unter der eingestellten max. Ladespannung (bei mir 52.5V eingestellt) oder liege ich da falsch?

So ungefähr. Der Laderegler lädt mit voller Leistung bzw. vollem Strom bis zur Absorbtion Voltage (keine Ahnung, wie die auf Deutsch heißt) und lädt dann mit Konstantspannung, bis der Strom so klein ist, dass er auf die Float-Voltage geht.

> Die 0 sollten keine Probleme machen.

Doch, das überarbeitete DPL-Einstellungs-Design lässt nur noch "plausible" Spannungswerte zu, also 16 bis 66V. Ich hatte in meiner Original-Antwort auch von Null geschrieben und wollte dann die Grenze für den Wert anpassen, aber dann war ich der Meinung, dass es ja auch wunderbar mit großen Werten funktioniert und daher ein Aufweichen der Grenzen nicht nötig ist.

**Comment by schlimmchen** [comment]
> Kann es daran liegen, dass er dann immer vom Nacht in den Tag Modus springt??

Ja, das ist auch meine Einschätzung. Deine Batterie war zwar nicht leer zu diesem Zeitpunkt, aber auch nicht voll, also die Start Threshold war nicht erreicht. D.h. der DPL konnte nur die verfügbare solare Leistung einstellen am Wechselrichter immer wenn von dort mind. 20W kamen, weil Solar-Passthrough so funktioniert. Aber sobald es dann weniger als 20W waren, wird "battery discharging" erlaubt, weil ja Nacht ist und du "empty at night" eingestellt hast.

Vielen Dank für den Log und den Screenshot, so konnte man das schnell erklären.

Mach gerne ein neues Issue auf in dem du dir wünschst, dass der Cut-Off für Solar-Passthrough bzw. die Nutzung der Batterie an die Zeit geknüpft ist und dann nur einmal stattfindet. Das steht inzwischen auch so als TODO im Code:

https://github.com/helgeerbe/OpenDTU-OnBattery/blob/7d4a30dde43667dbf91ba988df499ee917717486/src/PowerLimiter.cpp#L254-L260

Ich erlaube mir, dieses Issue nochmal zu schließen, weil ich mir sicher bin, dass 66V als full solar passthrough start und stop Schwelle sowie die Null bei SoC full solar passthrough Schwelle in der Tat die Lösung ist für deine ursprüngliche Anfrage.
