### ISSUE TITLE
[Request] Cut-Off für Solar-Passthrough via sunset / sunrise (anstatt 20 W Schwelle)

### ISSUE THREAD

**Issue by ottelo9** [helgeerbe/OpenDTU-OnBattery#776]
### Is your feature request related to a problem? Please describe.

https://github.com/helgeerbe/OpenDTU-OnBattery/issues/773#issuecomment-2007952869

### Describe the solution you'd like

Cut-Off für Solar-Passthrough bzw. die Nutzung der Batterie an die Zeit (sunrise/sunset) knüpfen. Somit wird gewährleistet, dass der Cut-Off für Solar-Passthrough nur fix nur einmal stattfindet. 

https://github.com/helgeerbe/OpenDTU-OnBattery/blob/7d4a30dde43667dbf91ba988df499ee917717486/src/PowerLimiter.cpp#L254-L260

**Comment by schlimmchen** [comment]
Siehe auch #671 (habe ich gerade wiederentdeckt...) :speak_no_evil:

**Comment by ottelo9** [comment]
Stimmt hab ich letztens auch erst gelesen. Gehirn …

**Comment by AndreasBoehm** [comment]
Sollte sich erledigt haben wenn https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1126 gemerged wurde
