### ISSUE TITLE
Wechselrichter speist nach update nur noch die hälfte vom Verbrauch ein

### ISSUE THREAD

**Issue by Marc2805** [helgeerbe/OpenDTU-OnBattery#781]
### What happened?

seit dem update speist mein Hoymiles HM-1500 nur noch die hälfte vom Wert des Power Meter ein.

### To Reproduce Bug

Nach update

### Expected Behavior

selbe Leistung wie Power Meter

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

	2024.03.07

**Comment by spcqike** [comment]
Kann es sein dass du nicht alle MPPT angeschlossen hast? Dass du nur Eingang 1 und 2 oder 3 und 4 benutzt?

**Comment by Marc2805** [comment]
Ja habe 2 Eingänge sprich 1 MPPT angeschlossen sobald ich den 2. Parallel anschließe steigt der WR aus .
war aber vor dem update genauso, vor dem update hatte der WR immer den doppelten wert vom EM

**Comment by spcqike** [comment]
Die Skalierung wurde geändert. Und für Modelle mit mehreren Eingängen pro MPPT (HM Serie mit 4 Eingängen und HMT Serie) deaktiviert. Weil die Skalierung bei den Benutzern vermehrt Probleme gemacht hat. 

Dass dein wechselrichter mit einem Eingang pro MPPT oder auch mit allen 4 Eingängen aussteigt, ist allerdings komisch. Das höre ich zum ersten Mal. 

Kannst du das Verhalten genauer beschreiben? Was passiert genau, bzw. Was passiert nicht? 

Es gibt viele Leute, die einen HM-1500 mit allen 4 Eingängen an einer Batterie betreiben.

**Comment by schlimmchen** [comment]
> Es gibt viele Leute, die einen HM-1500 mit allen 4 Eingängen an einer Batterie betreiben.

Dazu gehöre ich, keine Probleme.

Bitte schließe alle Eingänge an die Batterie an.

**Comment by Marc2805** [comment]
Ich hatte die ganze zeit das Problem das wenn ich alle 4 Eingänge vom WR benutzt habe, der Wechselrichter zwar grün geblinkt hat aber er nicht mehr Starten wollte. Hab es jetzt noch einmal getestet und siehe da jetzt passt es. Warum auch immer .
Nochmal Vielen dank für die Hilfe
