### ISSUE TITLE
Avoid battery discharge on scheduled inverter reset if lower discharge limit was already reached

### ISSUE THREAD

**Issue by markusdd** [helgeerbe/OpenDTU-OnBattery#844]
### What happened?

Currently there is a significant discharge event when the inverter restarts at night to reset the daily values:
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/25175069/fc27a899-b3b6-4928-8b14-b8949c4b56b9)

This should not be happening if the discharge SoC limit (in my case 20%) is already reached.

### To Reproduce Bug

schedule inverter reset while Battery is already sitting at discharge limit

### Expected Behavior

probably the right approach would be to send persistent lowest limit to inverter, then issue restart, and the re-adjust to whatever it was before to avoid that spike.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

https://github.com/helgeerbe/OpenDTU-OnBattery/releases/tag/2024.03.07

**Comment by spcqike** [comment]
> probably the right approach would be to send persistent lowest limit to inverter, then issue restart, and the re-adjust to whatever it was before to avoid that spike.

how often can you write to the persistent memory? It this discharge worth the hassle and risk? Like 2.000W for 1min is worth 33.33Wh. That 0.7% of a 4.8kWh battery. How long is the restart and the discharge spike? 

Anyway, wouldn’t it be better to just set a persistent low limit once, and only work with non-persistent higher loads? Imagine your inverter resets for whatever reason and your DTU is broken / not responsive to stop it from discharging.

**Comment by markusdd** [comment]
> > probably the right approach would be to send persistent lowest limit to inverter, then issue restart, and the re-adjust to whatever it was before to avoid that spike.
> 
> how often can you write to the persistent memory? It this discharge worth the hassle and risk? Like 2.000W for 1min is worth 33.33Wh. That 0.7% of a 4.8kWh battery. How long is the restart and the discharge spike?
> 
> Anyway, wouldn’t it be better to just set a persistent low limit once, and only work with non-persistent higher loads? Imagine your inverter resets for whatever reason and your DTU is broken / not responsive to stop it from discharging.

valid points tbh.

it would equal to a write per day, not sure what type of Flash they use and if they have a littleFS or something to balance wear.

Maybe the better idea would be to offer this as an option next to the inverter reset, something as 'keep inverter limit at minimum to avoid discharge at reset'. Enabling this would then write the lowest limit as persitent once upon save and use it going forward, not daily.

I'm not particulary concerned in my setup about this as it is a large US5000 pack with plenty of margin til empty, but people with smaller Batteries or deeper DoD might be more concerned with this.

So this is more about thinking how we can make handling of this more user friendly.

**Comment by Manos1966** [comment]
> how often can you write to the persistent memory? 

very, very good point... no risks please 😨 

3,55A x 48V = 170W for a few seconds until the OpenDTUonBattery sends the new limit.

I am actually even happier to see that the Hoymiles did not reach "Full Power" during the startup sequence 👍

**Comment by markusdd** [comment]
> > how often can you write to the persistent memory?
> 
> very, very good point... no risks please 😨
> 
> 3,55A x 48V = 170W for a few seconds until the OpenDTUonBattery sends the new limit.
> 
> I am actually even happier to see that the Hoymiles did not reach "Full Power" during the startup sequence 👍

I don't think we can say that for sure.
I observed this varies a bit by day so I have seen seeper spikes as well. I assume it goes to full 800W for a certain span. But as 5s is usually the reporting interval this might not get captured.

**Comment by Manos1966** [comment]
@markusdd Do I see the graph correctly, the peak happened within a 10 second timeframe?

I would not add any changes for something that occured only for a few seconds.

**Comment by spcqike** [comment]
Ne neither. 

And, you can always set a lower permanent limit. So that after DC reconnect (or software restart) the inverter starts with allowed limit. If it should start to produce energy, the DPL will give it a higher, non persistent limit as needed.

**Comment by markusdd** [comment]
As said, I just wanted to bring this to attention. For my setup it is not an issue, but people with smaller batteries or very deep DoD settings might look at that differently.

The most realistic problem that could occur is tripping the BMS of the connected battery. Then it does not matter is this only occurs for a couple of seconds.

I'm fine with not changing the code but that behavior should at least be documented somehow so that people e.g. can set lower persistent limits

**Comment by schlimmchen** [comment]
> but that behavior should at least be documented somehow

Yes, I agree. Adding something to the documentation was also in my head. I thought about putting it next to the explanation of the auto-restart function. It would be great if it was part of the "setup checklist", but there is nothing like it, AFAIK.

**Comment by Manos1966** [comment]
@markusdd It was not meant a critic Markus. I am happy that somebody spent the time and gathered some data.

I always knew it, this is the normal way the Hoymiles starts (goes to full power).
What I also know was that it does not jump to full power immediately, rather it gradually increases power.
I am curious to see how long it takes the Dynamic Power Limiter to start regulating the Hoymiles.

I also have the restart of the Hoymiles at 08:00 which means my battery is actually going to be empty after a night's work. I do not let my battery below 15% but still, it good to keep this in mind.

So your mention is well taken, I will see where I can put a note about this in the Wiki.

**Comment by markusdd** [comment]
not taken as criticism, I think the NVM wear-out argument is very valid and we should not do that.
afaik the regulating loop of th HM series is somewhere between 20-30 seconds, so it's not long on a total scale, still significant though for a discharged battery.

maybe a comment in the UI next to the restart enable which enables the restart would be good?

But I agree a general 'items to be considered' list would help here.

**Comment by Manos1966** [comment]
@spcqike 

> Anyway, wouldn’t it be better to just set a persistent low limit once, and only work with non-persistent higher loads? Imagine your inverter resets for whatever reason and your DTU is broken / not responsive to stop it from discharging.

Wird es funktionieren?
- Persistant 300W
- Wird der DPL danach trotzdem bis 1500W (z.Beispiel) dynamisch regeln?
- ...und beim Neustart geht die Hoymiles nur auf 300W bis der DPL anfaengt wieder zu regeln?  

Das waere Super! 🤩

**Comment by schlimmchen** [comment]
> Das waere Super! 🤩

Naja, das ist genau worüber wir reden, das funktioniert so. Jedenfalls nehme ich das fest an.

> maybe a comment in the UI next to the restart enable which enables the restart would be good?

If the hint bubble would not be so large already, then yes.

![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3578416/3cc4110b-e4c1-4708-bf11-639a95e2d964)

I am thinking about replacing some of these hints to be links to the respective part of the documentation. What do you think about that idea?

**Comment by spcqike** [comment]
> Wird es funktionieren?

Ich gehe davon aus. 

Theoretisch macht es aus Gründen der (Batterie)Sicherheit (tiefenentladeschutz) halt auch Sinn das lower limit des DPL als persistentes Limit zu übertragen. Oder sogar noch kleinere werte. 

Warum sollte der inverter im worstcase nach einem Neustart einfach 100% fahren und die Batterie krampfhaft entleeren? 

Bei meinen rein PV Systemen ist mir das quasi egal (: aber mit ner Batterie? Da hätte ich längst 50W persistent hinterlegt :)

**Comment by schlimmchen** [comment]
> Da hätte ich längst 50W persistent hinterlegt :)

Und ich wünschte, wir könnten das wissen und im Code verarbeiten. Dann könnten wir im DPL pauschal ein persistentes Limit setzen, wenn festgestellt wird, dass der Inverter kein persistentes Limit kennt bzw. dass es hoch ist (höher als unteres Limit dachte ich). Ich hab noch nicht genau geschaut, aber ich vermute diese Info haben wir nicht (auf der Grundlage, dass sie irgendwo angezeigt würde im Web Interface).

**Comment by schlimmchen** [comment]
I consider this completed by [this commit in the docs repo](https://github.com/schlimmchen/OpenDTU-OnBattery-docs/commit/e52cead3c1d73f52d682ef3dc8d8649cbc67725d), deployed to [opendtu-onbattery.net](https://opendtu-onbattery.net/firmware/configuration/dpl/#automatic-restart-time):

![image](https://github.com/user-attachments/assets/d32ca785-a631-47ea-87db-a40bc586976a)

Please do complain if you think that is insufficient.
