### ISSUE TITLE
Live-Ansicht: "Huawei AC Leistung" = "Huawei DC Leistung"

### ISSUE THREAD

**Issue by Linos88** [helgeerbe/OpenDTU-OnBattery#846]
### What happened?

Hallo,
nur ein kleiner Schönheitsfehler :-)
In der Live-Ansicht unter "Huawei **AC** Leistung" wird die DC-Leistung angezeigt

<img width="1702" alt="Bildschirmfoto 2024-04-05 um 13 18 51" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/83694034/462e0ddf-507e-4cfb-930e-b69c0799fbbd">

### To Reproduce Bug

siehe Live-Ansicht

### Expected Behavior

Umbenennen oder Anzeigewert ändern

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.03.07

**Comment by schlimmchen** [comment]
@Linos88 Kannst du bitte meinen vorgeschlagenen Fix aus #866 testen? Dort gibt es auch fertige [Firmware aus dem PR-Build Run](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/8642597461?pr=866).

**Comment by Linos88** [comment]
@schlimmchen sieht gut aus

<img width="1285" alt="Bildschirmfoto 2024-04-11 um 13 57 43" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/83694034/a4635af2-21d3-44e1-9a56-f69974e56df6">
