### ISSUE TITLE
[Request] MQTT battery provider JSON parsing (Zendure SolarFlow hub support)

### ISSUE THREAD

**Issue by Meatstake** [helgeerbe/OpenDTU-OnBattery#897]
### Is your feature request related to a problem? Please describe.

I wonder if it would be possible to add a support of the Zendure SolarFlow hubs to get the battery data from them and organise a full solar bypass if the battery is by 100%. 

### Describe the solution you'd like

The esp reads battery level from Zendure hub. If battery level is by 100% and the hub does not charge it anymore (it is important, because the %-measurement of this system is not reliable), then the Hoyemiles inverter is set to the value, that allows a pass through of all the produced solar energy till the battery starts to discharge itself. When the battery starts to discharge itself, then at first, the solar bypas value sets itself to the lower level, allowing to charge the battery, and if it does help, and the battery does not charge, but gets further discharged (sunset, clouds etc.), then everything just returns to normal mode. Till the battery is 100% and not charged again.

**Comment by schlimmchen** [comment]
Please provide information on how the communication with the Zendure SolarFlow Hub works. Serial? CAN? Bluetooth? HTTP? MQTT?

Also explain what that product does. Is it "only" a battery with an internal BMS?

Is there a Victron charge controller with VE.Direct available in this setup to realize solar-passthrough?

**Comment by apss-fuchs** [comment]
MQTT can be used for this.
See here: https://github.com/z-master42/solarflow/blob/main/solarflow.md

The Field "electricLevel" is battery level

It can read from the [appKey]/[deviceID]/state

Example:
{
  "outputHomePower": 199,
  "packInputPower": 208,
  "electricLevel": 64,
  "sn": "ABC"
}

**Comment by danny1605** [comment]
It would be great if Zendure were available in OpenDTU via MQTT.

**Comment by apss-fuchs** [comment]
@schlimmchen Can we extend the JSON field with a JSON variable?

**Comment by schlimmchen** [comment]
I'm not sure that I can follow...

You need the MQTT battery provider to parse JSON in the payload published to the respective topic? Similar to the HTTP+JSON power meter implementation?

**Comment by apss-fuchs** [comment]
@schlimmchen Yes, but the JSON is in in the MQTT topic. 
We need to configure a JSON path inside the MQTT topic.
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/95090185/299ee491-579d-4815-b250-561e974e3fb5)

**Comment by schlimmchen** [comment]
Alright, that's straight-forward. I did the work required in preparation for this already in the context of the powermeter refactoring, which lands eventually. In there I also added parsing JSON payload to the MQTT power meter implementation. We can do the same here. Please stand by, I'll trigger you to have you test it once the refactor is ready.

**Comment by danny1605** [comment]
Hello, is there any news yet? I would offer to test it out

**Comment by TvT73** [comment]
Oh das würde mich auch interessieren. Zumal der Zendure bei mir nur an 2 von den 4 MPPT Trackern läuft (HMS-18004T)

**Comment by switchtheflip** [comment]
Das wäre ein grandioses feature!

Anscheinend hat sich schon mal jemand die Zendure-Kommunikation angesehen, sogar unter Umgehung von Cloud und App, vielleicht hilf das hier:

https://github.com/reinhard-brandstaedter/solarflow-bt-manager

**Comment by apss-fuchs** [comment]
@schlimmchen any updates on this?

**Comment by schlimmchen** [comment]
![image](https://github.com/user-attachments/assets/7843f9ff-da32-4fa5-9940-3525551fade7)

I'll prioritize this. Expect an invitation to test a pull request build in the near future, maybe tonight.
