### ISSUE TITLE
Power Meter Seriell Lesekopf Fehler

### ISSUE THREAD

**Issue by andy75andreas** [helgeerbe/OpenDTU-OnBattery#902]
### Is your feature request related to a problem? Please describe.

Der Wert vom Power Meter seriell Lesekopf wir manchmal nicht richtig angezeigt.
Baulich bedingt habe ich zwischen DTU und Zählerschrank 10m Kabel.
Die serielle Verbindung funktioniert soweit gut, bis auf ein paar Fehler über den Tag verteilt.
Ich habe durch zufall 2x so winen Fehler gesehen.
Ich habe lt. Anzeige für einen kurzen Moment 283 Trillarden Watt verbraucht. (283.001.200.100.000,00W) .

Hier sollte eine Plausibilitätsüberprüfung der Daten gemacht werden.
Also nicht einfach Anzeigen und verarbeiten sondern wenn größer 20kW (sollte reichen) dann den Wert verwerfen.
Die Visualisierung zerhaut das dann leider ganz ordentlich.

![Screenshot 2024-04-21 200558](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/47005753/50e2c26d-e7d5-4c28-8a8d-1d9772239fc4)
![Screenshot_20240420_083401_Firefox](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/47005753/f7aa960f-c846-45f7-bd5d-4fc08045e4af)
![Screenshot_20240421_075834_Firefox](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/47005753/333757ac-8870-40b4-bf09-8f4e49568b29)

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by spcqike** [comment]
Du solltest deine Abfrage verbessern. Woher auch immer die Fehler kommen 

ob man solch Probleme in der openDTU entgegenwirken muss? 

Auf jedenfall kannst du es in grafana ausblenden. Einfach dein query anpassen. Bspw 

> select mean(value) from DB where value < 20000 and $timefilter group by …..

wie auch immer dein query aussieht. Aber „where value < 20000“ sollte hier helfen die zu großen Werte gar nicht erst aus der Datenbank abzufragen.

**Comment by schlimmchen** [comment]
spcqike und ich haben eine ähnliche Einstellung hierzu: Die OpenDTU-OnBattery sollte nicht Fehler kaschieren, die woanders begründet sind.

In diesem Fall möchte ich die Schuld darauf schieben, dass das Protokoll womöglich keine Prüfsummenberechnung enthält. Das wäre der richtige Ansatz, solche Fehler zu vermeiden. Es kann allerdings auch sein, dass es eine Prüfsumme gibt, die aber eher schwach ist (scheint bei VE.Direkt auch so zu sein), sodass mehrere Fehler sich gegenseitig kaschieren können.

Problematischer finde ich die Tatsache, dass dein serielles Kabel 10m lang ist. Das ist natürlich nicht ideal. Ich behaupte, dass hier noch was rauszuholen ist. Was ist das denn für ein Kabel? Hat das eine gute Schirmung? Ist die Schirmung mit GND verbunden? Ist der Querschnitt der Adern großzügig? Hat der Lesekopf auch einen Pegel von 3V3? Falls nicht, installiere bitte einen ADUM1201 dazwischen. Vermeide es, das Kabel neben stromführenden Leitungen zu verlegen. Schlimmstenfalls solltest du RS485 Umsetzer in Betracht ziehen, also sowohl am IR-Lesekopf als auch am ESP32 einen RS485 Transceiver installieren, sodass auf den 10m RS485 läuft. Dann ist in jedem Fall Ruhe insofern, als dass Übertragungsfehler ausgeschlossen sein dürften.

Bis dahin solltest du den Vorschlag von spcqike annehmen, und den Query zur Erzeugung deines Grafen anpassen, um deine Daten zu bereinigen.

**Comment by andy75andreas** [comment]
Ok, ich werde mal den RS485 auf beiden Seiten meiner "langen" Leitung einbauen.
Bis dahin wie muss die Abfrage in Grafana angepasst werden?

Meine Abfrage sieht momentan wie folgt aus:
`from(bucket: "iobroker")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mqtt.0.dtu.open.powermeter.power1")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")`

**Comment by spcqike** [comment]
Mit Flux 2.0 hab ich es selber noch nicht gemacht, aber irgendwie so 

> from(bucket: "your_bucket")
  |> range(start: -1h)
  |> filter(fn: (r) => r._value <= 20000.0)

also, die r._value filter einbauen in deinen query.

**Comment by andy75andreas** [comment]
Der Filter und die 2 RS485 Wandler haben 1a funktionert.

Mein Grafana Script (Flux 2.0) habe ich dank der Hilfe von "spcqike" folgendermasen angepasst:

`from(bucket: "iobroker")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._value <= 20000.0)
   |> filter(fn: (r) => r._value >= -1000.0)
  |> filter(fn: (r) => r["_measurement"] == "mqtt.0.dtu.open.powermeter.power1")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")`

![Screenshot 2024-04-23 193501](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/47005753/ea4927e0-ce12-4e87-8f32-32c787029878)

**Comment by schlimmchen** [comment]
Super cool, du hast unsere Hilfe ernst genommen und umgesetzt, und das mit Erfolg. Da hilft man doch gerne!

**Comment by schlimmchen** [comment]
Da ich es inzwischen genauer weiß, möchte ich hier festhalten:

Im SML Datenpaket ist eine Prüfsumme vorgesehen. Ich nehme an, dass jeder dieser Leseköpfe diese Prüfsumme auch berechnet und mitschickt. Allerdings wurde diese bisher nicht betrachtet. Stattdessen wurden alle Felder, die irgendwie nach Daten aussahen, dekodiert und die Werte wurden sofort übernommen.

Mit dem "Power Meter Refactoring", das ich gerade durchführe, wird das aufhören. Daten werden nur noch übernommen, wenn die Prüfsumme korrekt war. Dann würden die hier beschriebenen falschen Werte mit hoher Wahrscheinlichkeit ausgefiltert (weil die Prüfsumme CRC16 ist, also vergleichsweise stark).
