### ISSUE TITLE
WR detail view is missing

### ISSUE THREAD

**Issue by Rolober** [helgeerbe/OpenDTU-OnBattery#907]
### What happened?

Hello
on live view I go no details of the WR, only "Warte auf Daten". Also the "P" is missing. Could you help?

Rolober
![Screenshot 2024-04-22 083758](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/167742255/17b9a90d-ba23-4b5c-b334-c508d2e7c48d)

### To Reproduce Bug

alway missing

### Expected Behavior

n/a

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

	2024.03.23

**Comment by Rolober** [comment]
Why work the FW version 2024.01.26 with the HMS?

**Comment by Rolober** [comment]
thx, migsun. No, the same issue appears. Missing of panels detail etc.

![Screenshot 2024-04-22 083758](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/167742255/d777395b-b1bc-4708-93ed-a973182790e3)

**Comment by schlimmchen** [comment]
Continued in #912.
