### ISSUE TITLE
DPL sets persist and non-persistend limits at the same time?

### ISSUE THREAD

**Issue by greymda** [helgeerbe/OpenDTU-OnBattery#914]
### What happened?

I was looking into history on HA that receives messages via MQQT from OpenDTU-OnBattery and notices that DPL sets both persistent AND non-persistent limits at the same time. Is it expected so? 
Read somewhere that setting PERSISTENT limits often will harm the inverter after a while.

Cheers

<img width="869" alt="Screenshot 2024-04-23 at 15 54 38" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/9991596/2ad2c65a-ba49-4d2f-a364-1b0767f51d09">

### To Reproduce Bug

<img width="1231" alt="Screenshot 2024-04-23 at 15 58 25" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/9991596/5d664e58-c05d-4f22-b4eb-69ec5954d9c6">

### Expected Behavior

OpenDTU-OnBattery sets only non-persistent limit

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.03.23

**Comment by Manos1966** [comment]
Vielleicht ist hier die Erklaerung:

https://github.com/tbnobody/OpenDTU/issues/1304
