### ISSUE TITLE
[Request] Improvement of the DPL algorithm in case of shading of one of the MPPTs

### ISSUE THREAD

**Issue by greymda** [helgeerbe/OpenDTU-OnBattery#917]
### Is your feature request related to a problem? Please describe.

Curiosly, i've noticed that the when a DPL limit is set, in my case (see the attached picture) say 104W the load is divided for the available MPPTs (HM-800 case) hence MPPT1 is limited to 52W and MPPT2 to another 52W. The expectation of the algorithm is that both MPPT can deliver, BUT this is not always the case- shades and so on.
In this particular situation, because MPPT2 can't deliver what it's being asked for (only 17W from the demanded 52W) we have grid consumption 55W (all in the picture attached)
<img width="1426" alt="Screenshot 2024-04-24 at 16 42 00" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/9991596/8b7ac4a2-8c9f-49ef-9305-8b5bfdf8310f">

### Describe the solution you'd like

The ask: check the real delivered energy from MPPTs and if one is much lower than the other - adjust the total DPL limit value upwards, basically what OpenDTU-OnBattery currently does when there's no input from a MPPT and scales the limit to 2x value, but this enhancement should use a variable scaling, depending on the real output of the lower MPPTs (in my case String Dois).
Hope this makes sense and you see any value from this enhancement.

**Comment by greymda** [comment]
maybe in context of implementing enhancement https://github.com/helgeerbe/OpenDTU-OnBattery/issues/899 it would make sense since any change in cloudiness/etc would be reflected at a higher rate/precision.

**Comment by greymda** [comment]
@schlimmchen how do you feel about this?

**Comment by greymda** [comment]
Fair enough, thanks

**Comment by saschaabraham** [comment]
Maybe it is posible to realise an option, to set the DLP to max limit value, if the powermeter is below zero and then decrease the inverter limit step by step to reach the wanted value. This could compensate the shading in an appropiate way. and should bounded to the solar powered option.
