### ISSUE TITLE
DEBO OLED 2.42

### ISSUE THREAD

**Issue by lopo2005de** [helgeerbe/OpenDTU-OnBattery#926]
### Is your feature request related to a problem? Please describe.

Erst einmal ganz vielen Dank für OpenDTU!!!
Das kleine 0.9 OLED ist wirklich sehr klein.
Ich würde gern das DEBO OLED 2.42 von JOY-IT anschliessen, per I2C sollte das kein Problem sein.
Bei der gleichen Auflösung müsste ich vermutlich die Schriftgrösse gar nicht ändern.
Nur:
JOY-IT verwendet den Treiber SSD1309.
Muss der noch in das System eingepflegt werden oder wird so etwas per pin_mapping.json eingerichtet? 

### Describe the solution you'd like

DEBO OLED 2.42 von JOY-IT

**Comment by spcqike** [comment]
https://github.com/helgeerbe/OpenDTU-OnBattery/blob/4bc4defe665946d1c096206fb70682e31a004dd0/docs/DeviceProfiles/wt32-eth01.json#L54

Gibt es scheinbar bereits. Musst du nur richtig einstellen.

**Comment by lopo2005de** [comment]
Ist voll cool!!! Mit Ethernet würde mir auch noch gefallen!
Also: bestellen :)

**Comment by ingrimsch** [comment]
Ich habe ein SSD1309 2.42" OLED seit einiger Zeit laufen - funktioniert absolut problemlos. :)

Einfach als Display Type "4" einstellen und die korrekten Pins für DATA und CLK auswählen.

**Comment by schlimmchen** [comment]
Meiner Einschätzung nach ist hier von Seiten OpenDTU-OnBatery nichts zu tun. Schreibe wieder, falls dem nicht so ist.
