### ISSUE TITLE
[Request]More Data on the Startpage from the Battery - Voltage Diffence between 2 x 12V LiFePo4

### ISSUE THREAD

**Issue by fellpower** [helgeerbe/OpenDTU-OnBattery#954]
### Describe the solution you'd like

Im using 2 x 12V LifePo4 batteries in series - and i want to know, if they drift. is it possible to get that voltage / or the Error of the smartshunt on the startpage?

i have a Balancer, but its better to check than to trust ;)

**Comment by schlimmchen** [comment]
See #573. This will be merged eventually. The PR must be rebased onto the current development branch. Conflicts will need to be resolved. Not a priority issue for me. Maybe you can motivate someone else to pick up the work from #573?
