### ISSUE TITLE
DPL: Maximales Leistungslimit wird bei Skalierung nicht beachtet 

### ISSUE THREAD

**Issue by RoFranz** [helgeerbe/OpenDTU-OnBattery#974]
### What happened?

Werden nicht alle Eingänge des Wechselrichters bedient, wird das maximale Leistungslimit nicht beachtet. Das Leistungslimit ist dabei notwendig, damit die Akkus nicht über Ihren maximal zulässigen Entladestrom entladen werden.

### To Reproduce Bug

1. Leistungslimit auf 1300 stellen (HMS 1600-4t) -> entspricht 81.25%
![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/64327411/eaf44198-55da-4ed4-993c-e39a18aa801b)

2. Werden alle 4 Eingänge bedient (angeschlossene Akkus sind ON) -> keine Skalierung -> Leistungslimit wird eingehalten
![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/64327411/9abc52e7-d7d6-4482-8580-0e8a06be7a78)

3. werden nur 2 Eingänge bedient (ein Akku OFF) -> Skalierung erfolgt korrekt -> Leistungslimit wird überschritten (100%) 
![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/64327411/3a590712-f9dd-4f79-ac65-bc4e0152248e)

### Expected Behavior

Auch bei einer Skalierung wird das eingestellte Leistungslimit nicht überschritten

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.05.07

### Anything else?

Einfach danke an die fleißigen Programmierer und die Bereitschaft auch solche kleinen Bugs zu verbessern.
DANKE!

**Comment by spcqike** [comment]
Ich verstehe das Problem noch nicht ganz. 

800W AC sind doch <1300W Limit. Dass der DPL bei 2 von 4 aktiven Eingängen entsprechend höhere Werte einstellt, damit überhaupt ansatzweise 800W raus kommen, ist doch Sinn der Skalierung.

**Comment by RoFranz** [comment]
Danke für die Nachfrage und entschuldige, wenn ich es nicht gleich verständlich erklären konnte.
An dem Wechselrichter sind zwei Akkus (BP 2500 version 1), welche maximal 400W je Ausgang ausgeben können - ansonsten erfolgt "Notabschaltung".  Wenn der Wechselrichter mit 100% als Limit betrieben wird, können am Eingang des Wechselrichters durchaus mehr als die rechnerisch 400W (1600W durch 4) eingespeist werden. Zudem wie du bereits gesagt hast, kommt es sowieso zu einer Differenz zwischen Ausgangsleistung Akku <-> Eingangsleistung WR. Somit kommt es häufig zu einer Überlastung der Akkuausgänge (weil der WR mehr zieht als eingestellt). Dieses Zusammenspiel ist aber auch nur "mein" Problem und kann mittels einer IF-Abfrage innerhalb der DPL.cpp bisher auch gelöst werden.
Aber GENERELL: Sollte das eingestellte Leistungsmaximum des WR nicht unabhängig von der Einspeisung NIE überschritten werden. Ansonsten macht doch das Leistungslimit keinen Sinn, wenn es nicht GENERELL gilt?

**Comment by spcqike** [comment]
> Aber GENERELL: Sollte das eingestellte Leistungsmaximum des WR nicht unabhängig von der Einspeisung NIE überschritten werden. Ansonsten macht doch das Leistungslimit keinen Sinn, wenn es nicht GENERELL gilt?

ist glaube ich ne Philosophie Frage. Für mich war das bisher ein maximales AC ausgangslimit. Und das wird, soweit ich weiß, eingehalten. Mit Skalierung und auch ohne.

**Comment by RoFranz** [comment]
Ich denke dir für die Korrektur meines Blickwinkels!
Das es sich lediglich auf die AC Seite bezieht, steht auch bei euch so in der Erklärung.
Wer lesen kann, ist klar im Vorteil!
Danke!
